<a href="https://colab.research.google.com/github/talitharhmd/Tugas-Akhir/blob/main/Embedding_Cluster.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **00 Import Library**
Menginstall library yang dibutuhkan untuk proses embedding, reduksi dimensi, dan clustering.

In [1]:
# ================= INSTALL PACKAGE =================
!pip install gensim
!pip install umap-learn

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 37.5 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0
Requirement already satisfied: umap-learn in /usr/local/lib/python3.12/dist-packages (0.5.12)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (2.0.2)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (1.16.3)
Requirement already satisfied: scikit-learn>=1.6 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (1.6.1)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.6.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from umap-learn) (4.67.3)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.2->umap-learn) (0.43.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.12/dist-packages (from pynndescent>=0.5->umap-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6->umap-learn) (3.6.0)

In [2]:
# import libraries
import numpy as np
import pandas as pd
import ast
import os
import glob
import os
import gc

# embedding
from gensim.models import Word2Vec, FastText
from sklearn.metrics.pairwise import cosine_similarity

# reduksi dimensi
import umap
from sklearn.decomposition import PCA

# clustering
from sklearn.cluster import KMeans

# evaluasi clustering
from sklearn.metrics import silhouette_score, davies_bouldin_score

# preprocessing untuk cosine
from sklearn.preprocessing import normalize

In [3]:
import ast

# **04 Pembuatan Word Embedding**

## 4.1 Load Data Hasil LDA
Menggunakan dataset terbaik dari hasil LDA sebagai dasar embedding.

In [4]:
df = pd.read_csv('/content/lemmatization_nb5_na0.6 (3).csv')
df.head()

,doc_id,clean_text,lemmatization,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topik_dominan,prob_topik
0,0,today s digital world demands about automated ...,"['today', 'digital', 'world', 'demand', 'autom...",0.382534,0.516984,0.001629,0.002900,0.034902,0.001863,0.059188,2,0.516984
1,1,sentiment analysis sa is focused on mining opi...,"['sentiment', 'sa', 'focused', 'mining', 'opin...",0.266511,0.463015,0.000791,0.001397,0.083231,0.138796,0.046260,2,0.463015
2,2,aspect based sentiment analysis absa has recen...,"['aspect', 'sentiment', 'absa', 'recently', 'a...",0.651315,0.344010,0.000732,0.001291,0.001028,0.000838,0.000786,1,0.651315
3,3,in the era of web online forums blogs and twit...,"['era', 'web', 'online', 'forum', 'blog', 'twi...",0.001337,0.639947,0.001113,0.001969,0.270079,0.084360,0.001195,2,0.639947
4,4,financial and economic news is continuously mo...,"['financial', 'economic', 'news', 'continuousl...",0.361857,0.332745,0.000809,0.057704,0.001132,0.000926,0.244827,1,0.361857

In [5]:
# handle parsing token dengan aman
def safe_literal_eval(x):
    # handle NaN / None
    if pd.isna(x):
        return []

    # jika sudah list
    if isinstance(x, list):
        return x

    # jika string list
    try:
        return ast.literal_eval(x)
    except:
        # fallback: split biasa
        return str(x).split()

# apply ke kolom utama
df['tokens'] = df['lemmatization'].apply(safe_literal_eval)

# pastikan tidak ada token kosong
df = df[df['tokens'].map(len) > 0].reset_index(drop=True)

# set variabel utama
sentences = df['tokens']
original_text = df['clean_text']

In [6]:
sentences

0       [today, digital, world, demand, automated, sen...
1       [sentiment, sa, focused, mining, opinion, iden...
2       [aspect, sentiment, absa, recently, attracted,...
3       [era, web, online, forum, blog, twitter, becom...
4       [financial, economic, news, continuously, moni...
                              ...
5045    [purpose, examines, role, analytics, managemen...
5046    [controlled, environment, agriculture, cea, co...
5047    [debate, examines, climate, change, present, c...
5048    [hybrid, automated, machine, automl, architect...
5049    [traditional, nursing, practice, often, rely, ...
Name: tokens, Length: 5050, dtype: object

In [7]:
original_text

0       today s digital world demands about automated ...
1       sentiment analysis sa is focused on mining opi...
2       aspect based sentiment analysis absa has recen...
3       in the era of web online forums blogs and twit...
4       financial and economic news is continuously mo...
                              ...
5045    purpose this study examines the role of data a...
5046    the controlled environment agriculture cea sys...
5047    this debate examines how climate change presen...
5048    this research propose s a hybrid automated mac...
5049    traditional nursing practices often rely on em...
Name: clean_text, Length: 5050, dtype: object

## 4.1 Menentukan Dataset untuk Embedding

In [8]:
# folder penyimpanan embedding
os.makedirs("embedding_results/word2vec", exist_ok=True)
os.makedirs("embedding_results/fasttext", exist_ok=True)
os.makedirs("embedding_results/fast2vec", exist_ok=True)

In [9]:
# folder penyimpanan embedding
os.makedirs("word_embedding_results/word2vec", exist_ok=True)
os.makedirs("word_embedding_results/fasttext", exist_ok=True)
os.makedirs("word_embedding_results/fast2vec", exist_ok=True)

## 4.2 Konfigurasi Parameter Embedding
Menentukan parameter utama untuk training Word2Vec, FastText, dan Fast2Vec.

In [10]:
# parameter embedding
vector_dimensions = [100]
context_windows = [5, 10]

model_architecture = {
    "cbow": 0,
    "skipgram": 1
}

epochs = 15
min_word_frequency = 2
seed_value = 42
num_workers = 2

# khusus fast2vec
alpha_weights = np.round(np.arange(0.1, 1.0, 0.1), 1)

# rekap eksperimen
experiment_results = []
trained_word2vec_models = {}
trained_fasttext_models = {}

## 4.3 Dokumen Embedding
Mnegubah token menjadi vektor dokumen (rata-rata kata)

In [11]:
def build_document_vector(tokens, word_vectors):
    """
    Mengubah list token menjadi vektor dokumen dengan merata-rata vektor kata.
    model_wv: KeyedVectors (model.wv) dari Gensim
    """
    word_vecs = [word_vectors[word] for word in tokens if word in word_vectors]

    if len(word_vecs) == 0:
        return np.zeros(word_vectors.vector_size)

    return np.mean(word_vecs, axis=0).astype(np.float32)

## 4.4 Word2Vec Embedding
Melatih Word2Vec menggunakan dataset terbaik dan menyimpan hasil embedding serta parameter model.

In [12]:
print("--- MULAI EKSPERIMEN WORD2VEC ---")

preview_shown = False

total_models = (
    len(vector_dimensions) *
    len(context_windows) *
    len(model_architecture)
)

print(f"\n📊 total model word2vec yang akan dibentuk: {total_models}")

# loop parameter vector size
for vector_size in vector_dimensions:
    # loop parameter window
    for window_size in context_windows:
        # loop arsitektur model (cbow / skipgram)
        for arch_name, sg_flag in model_architecture.items():

            # 1. nama eksperimen
            experiment_id = f"W2V_{arch_name}_S{vector_size}_W{window_size}"
            print(f"\n⚙️ menjalankan: {experiment_id}")

            # 2. training model word2vec
            model = Word2Vec(
                sentences=sentences,
                vector_size=vector_size,
                window=window_size,
                min_count=min_word_frequency,
                sg=sg_flag,
                epochs=epochs,
                workers=num_workers,
                seed=seed_value
            )

            trained_word2vec_models[experiment_id] = model

            # 3. document embedding
            document_vectors = np.array([
                build_document_vector(doc, model.wv)
                for doc in sentences
            ], dtype=np.float32)

            # simpan skor rekap
            experiment_results.append({
                "model": "word2vec",
                "architecture": arch_name,
                "vector_size": vector_size,
                "window": window_size,
                "alpha": None,
                "beta": None
            })

            # hasil document embedding
            df_doc_embed = pd.DataFrame(
                document_vectors,
                columns=[f"dim_{i}" for i in range(vector_size)]
            )

            # metadata dokumen
            df_doc_embed.insert(0, "doc_id", df['doc_id'])
            df_doc_embed.insert(1, "clean_text", original_text.values)
            df_doc_embed.insert(2, "text_processed", sentences.apply(lambda x: " ".join(x)))

            # metadata eksperimen
            df_doc_embed.insert(3, "architecture", arch_name)
            df_doc_embed.insert(4, "vector_size", vector_size)
            df_doc_embed.insert(5, "window", window_size)

            # preview eksperimen
            if not preview_shown:
                print(f"\n📄 preview document embedding ({experiment_id})")
                display(df_doc_embed.head(3))
                preview_shown = True

            # simpan file document embedding
            df_doc_embed.to_csv(
                f"embedding_results/word2vec/doc_embedding_{experiment_id}.csv",
                index=False
            )

            del document_vectors, df_doc_embed
            gc.collect()

--- MULAI EKSPERIMEN WORD2VEC ---

📊 total model word2vec yang akan dibentuk: 4

⚙️ menjalankan: W2V_cbow_S100_W5

📄 preview document embedding (W2V_cbow_S100_W5)

,doc_id,clean_text,text_processed,architecture,vector_size,window,dim_0,dim_1,dim_2,dim_3,...,dim_90,dim_91,dim_92,dim_93,dim_94,dim_95,dim_96,dim_97,dim_98,dim_99
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,cbow,100,5,0.275636,-0.336439,0.281806,0.510947,...,-0.110353,0.422030,0.092907,-0.041191,0.086387,0.104363,-0.208253,0.175828,-0.569608,0.474026
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,cbow,100,5,-0.169865,-0.346782,0.068902,0.717927,...,-0.118891,0.228883,-0.013980,-0.095867,0.061363,0.151990,-0.478211,0.304970,-0.524348,0.279755
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,cbow,100,5,-0.107693,-0.720080,0.110628,0.709941,...,-0.390768,0.149861,0.139571,-0.261960,0.081571,0.360531,-0.708905,0.307770,-0.764275,0.418865

⚙️ menjalankan: W2V_skipgram_S100_W5

⚙️ menjalankan: W2V_cbow_S100_W10

⚙️ menjalankan: W2V_skipgram_S100_W10

Menampilkan kontribusi tiap kata terhadap vektor dokumen untuk validasi manual perhitungan embedding.

In [13]:
print("--- word embedding untuk Word2Vec ---")

preview_shown = False

for experiment_id, model in trained_word2vec_models.items():

    print(f"\n⚙️ menjalankan word embedding: {experiment_id}")

    word_vectors = model.wv
    vocab = list(word_vectors.index_to_key)
    sentences_words = sentences

    # mapping word → vector
    word_matrix = {w: word_vectors[w] for w in vocab}

    # ambil metadata dari experiment_id (BENAR)
    arch = experiment_id.split("_")[1]
    vector_size = int(experiment_id.split("_S")[1].split("_")[0])
    window = experiment_id.split("_W")[-1]

    # trace per document
    def build_trace(doc_tokens):
        trace_cols = []

        for i in range(word_vectors.vector_size):

            parts = [
                f"{w}*{word_matrix[w][i]:.6f}"
                for w in doc_tokens
                if w in word_matrix
            ]

            trace_cols.append(", ".join(parts))

        return trace_cols

    trace_data = [build_trace(doc) for doc in sentences_words]

    df_trace = pd.DataFrame(trace_data)
    df_trace.columns = [f"word_dim{i}" for i in range(word_vectors.vector_size)]

    # document metadata
    df_doc = pd.DataFrame({
        "doc_id": df["doc_id"],
        "clean_text": original_text.values,
        "text_processed": sentences.apply(lambda x: " ".join(x)),
        "architecture": arch,
        "vector_size": vector_size,
        "window": window
    })

    df_final = pd.concat([df_doc, df_trace], axis=1)

    if not preview_shown:
        print(f"\n📄 preview word embedding trace ({experiment_id})")
        display(df_final.head(2))
        preview_shown = True

    df_final.to_csv(
        f"word_embedding_results/word2vec/word_embedding_trace_{experiment_id}.csv",
        index=False
    )

    del df_final, df_trace
    gc.collect()

--- word embedding untuk Word2Vec ---

⚙️ menjalankan word embedding: W2V_cbow_S100_W5

📄 preview word embedding trace (W2V_cbow_S100_W5)

,doc_id,clean_text,text_processed,architecture,vector_size,window,word_dim0,word_dim1,word_dim2,word_dim3,...,word_dim90,word_dim91,word_dim92,word_dim93,word_dim94,word_dim95,word_dim96,word_dim97,word_dim98,word_dim99
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,cbow,100,5,"today*0.458382, digital*1.345522, world*3.5797...","today*-0.563319, digital*-0.731106, world*-0.6...","today*-0.311302, digital*0.311396, world*1.843...","today*-0.265652, digital*-0.626490, world*0.14...",...,"today*0.243226, digital*-0.230295, world*3.083...","today*0.245486, digital*0.842084, world*2.2204...","today*0.309391, digital*-0.117070, world*-1.95...","today*-0.832816, digital*-0.401884, world*-0.8...","today*-0.003359, digital*2.301523, world*1.294...","today*0.515344, digital*-1.480514, world*-1.21...","today*0.770448, digital*1.818056, world*-0.583...","today*-0.092895, digital*0.219219, world*-2.83...","today*-0.623283, digital*0.232746, world*0.204...","today*-0.200658, digital*-0.474690, world*-1.1..."
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,cbow,100,5,"sentiment*-0.520728, sa*-0.386532, focused*0.4...","sentiment*-3.258090, sa*-0.625017, focused*0.3...","sentiment*0.478133, sa*-0.170839, focused*0.28...","sentiment*2.947648, sa*1.408500, focused*0.436...",...,"sentiment*-1.858012, sa*0.274308, focused*0.15...","sentiment*0.269496, sa*1.167911, focused*0.994...","sentiment*-0.244459, sa*-0.506931, focused*-0....","sentiment*-0.728475, sa*0.177106, focused*-0.0...","sentiment*-1.997706, sa*0.399556, focused*-0.3...","sentiment*0.853283, sa*0.336171, focused*0.041...","sentiment*-3.978590, sa*-1.516536, focused*-0....","sentiment*0.041570, sa*0.051674, focused*-0.26...","sentiment*-0.024959, sa*-0.231744, focused*-1....","sentiment*-0.591185, sa*-0.912045, focused*1.4..."

⚙️ menjalankan word embedding: W2V_skipgram_S100_W5

⚙️ menjalankan word embedding: W2V_cbow_S100_W10

⚙️ menjalankan word embedding: W2V_skipgram_S100_W10

## 4.5 FastText Embedding
Melatih FastText dengan parameter yang sama untuk dibandingkan dengan Word2Vec.

In [14]:
print("--- MULAI EKSPERIMEN FASTTEXT ---")

preview_shown = False

total_models = (
    len(vector_dimensions) *
    len(context_windows) *
    len(model_architecture)
)

print(f"\n📊 total model fasttext yang akan dibentuk: {total_models}")

# loop parameter vector size
for vector_size in vector_dimensions:
    # loop parameter window
    for window_size in context_windows:
        # loop arsitektur model (cbow / skipgram)
        for arch_name, sg_flag in model_architecture.items():

            # 1. nama eksperimen
            experiment_id = f"FT_{arch_name}_S{vector_size}_W{window_size}"
            print(f"\n⚙️ menjalankan: {experiment_id}")

            # 2. training fasttext model
            model = FastText(
                sentences=sentences,
                vector_size=vector_size,
                window=window_size,
                min_count=min_word_frequency,
                sg=sg_flag,
                epochs=epochs,
                workers=num_workers,
                seed=seed_value,

                # parameter subword
                min_n=3,
                max_n=6
            )

            trained_fasttext_models[experiment_id] = model

            # 3. document embedding
            document_vectors = np.array([
                build_document_vector(doc, model.wv)
                for doc in sentences
            ], dtype=np.float32)

            # 4. simpan rekap eksperimen
            experiment_results.append({
                "model": "fasttext",
                "architecture": arch_name,
                "vector_size": vector_size,
                "window": window_size,
                "alpha": None,
                "beta": None
            })

            # 5. dataframe document embedding
            df_doc_embed = pd.DataFrame(
                document_vectors,
                columns=[f"dim_{i}" for i in range(vector_size)]
            )

            # metadata dokumen
            df_doc_embed.insert(0, "doc_id", df['doc_id'])
            df_doc_embed.insert(1, "clean_text", original_text.values)
            df_doc_embed.insert(2, "text_processed", sentences.apply(lambda x: " ".join(x)))

            # metadata eksperimen
            df_doc_embed.insert(3, "architecture", arch_name)
            df_doc_embed.insert(4, "vector_size", vector_size)
            df_doc_embed.insert(5, "window", window_size)

            # 6. preview hasil pertama
            if not preview_shown:
                print(f"\n📄 preview document embedding ({experiment_id})")
                display(df_doc_embed.head(3))
                preview_shown = True

            # 7. simpan hasil
            df_doc_embed.to_csv(
                f"embedding_results/fasttext/doc_embedding_{experiment_id}.csv",
                index=False
            )

            # 8. memory cleanup
            del document_vectors, df_doc_embed
            gc.collect()

--- MULAI EKSPERIMEN FASTTEXT ---

📊 total model fasttext yang akan dibentuk: 4

⚙️ menjalankan: FT_cbow_S100_W5

📄 preview document embedding (FT_cbow_S100_W5)

,doc_id,clean_text,text_processed,architecture,vector_size,window,dim_0,dim_1,dim_2,dim_3,...,dim_90,dim_91,dim_92,dim_93,dim_94,dim_95,dim_96,dim_97,dim_98,dim_99
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,cbow,100,5,0.521053,-0.091690,0.592672,-0.742798,...,0.536281,-1.206319,0.161135,-0.069613,-0.037816,-0.034172,0.371773,-0.515796,0.427341,-0.036084
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,cbow,100,5,0.293021,-0.173066,0.173627,-0.288984,...,0.437439,-0.550900,-0.233010,0.247906,-0.525452,-0.331389,-0.019026,-0.575681,-0.130013,-0.149239
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,cbow,100,5,0.440959,0.032199,0.039709,-0.649122,...,0.499442,-0.924151,-0.616623,0.244300,-0.433321,0.028894,-0.204476,-0.312681,-0.156317,-0.622476

⚙️ menjalankan: FT_skipgram_S100_W5

⚙️ menjalankan: FT_cbow_S100_W10

⚙️ menjalankan: FT_skipgram_S100_W10

Menampilkan representasi embedding FastText berbasis karakter n-gram untuk mendukung interpretasi perhitungan embedding.

In [15]:
print("--- word embedding untuk FastText ---")

preview_shown = False

# generate subword manual sesuai konsep fasttext
def generate_subwords(word, min_n=3, max_n=6):
    word = f"<{word}>"
    subwords = []

    for n in range(min_n, max_n + 1):
        for i in range(len(word) - n + 1):
            subwords.append(word[i:i+n])

    return subwords

# loop semua model fasttext hasil training
for experiment_id, model in trained_fasttext_models.items():

    # ambil word vectors
    word_vectors = model.wv
    vocab = list(word_vectors.index_to_key)

    # ambil data dokumen
    sentences_words = sentences

    # parsing metadata eksperimen
    arch = experiment_id.split("_")[1]
    window = experiment_id.split("_W")[-1]

    print(f"\n⚙️ menjalankan word embedding fasttext: {experiment_id}")

    # mapping word → vector
    word_matrix = {w: word_vectors[w] for w in vocab}

    # build trace per dokumen
    def build_trace(doc_tokens):

        trace_cols = []

        for i in range(word_vectors.vector_size):

            parts = []

            for w in doc_tokens:

                if w in word_matrix:

                    # ambil subword (manual)
                    subwords = generate_subwords(w, min_n=3, max_n=6)

                    # batasi supaya tidak terlalu panjang (opsional)
                    subwords = subwords[:5]

                    parts.append(
                        f"{w}({','.join(subwords)})*{word_matrix[w][i]:.6f}"
                    )

                else:
                    parts.append(f"{w}(oov)*0.0")

            trace_cols.append(", ".join(parts))

        return trace_cols

    # generate trace seluruh dokumen
    trace_data = [build_trace(doc) for doc in sentences_words]

    df_trace = pd.DataFrame(trace_data)
    df_trace.columns = [f"word_dim{i}" for i in range(word_vectors.vector_size)]

    # metadata dokumen
    df_doc = pd.DataFrame({
        "doc_id": df["doc_id"],
        "clean_text": original_text.values,
        "text_processed": sentences.apply(lambda x: " ".join(x)),
        "architecture": arch,
        "vector_size": word_vectors.vector_size,
        "window": window
    })

    # gabungkan metadata + trace
    df_final = pd.concat([df_doc, df_trace], axis=1)

    # preview sekali saja
    if not preview_shown:
        print(f"\n📄 preview fasttext word + subword trace ({experiment_id})")
        display(df_final.head(2))
        preview_shown = True

    # simpan hasil
    df_final.to_csv(
        f"word_embedding_results/fasttext/word_embedding_trace_{experiment_id}.csv",
        index=False
    )

    # cleanup memory
    del df_final, df_trace
    gc.collect()

--- word embedding untuk FastText ---

⚙️ menjalankan word embedding fasttext: FT_cbow_S100_W5

📄 preview fasttext word + subword trace (FT_cbow_S100_W5)

,doc_id,clean_text,text_processed,architecture,vector_size,window,word_dim0,word_dim1,word_dim2,word_dim3,...,word_dim90,word_dim91,word_dim92,word_dim93,word_dim94,word_dim95,word_dim96,word_dim97,word_dim98,word_dim99
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,cbow,100,5,"today(<to,tod,oda,day,ay>)*-0.660936, digital(...","today(<to,tod,oda,day,ay>)*-0.462538, digital(...","today(<to,tod,oda,day,ay>)*1.561529, digital(<...","today(<to,tod,oda,day,ay>)*0.844327, digital(<...",...,"today(<to,tod,oda,day,ay>)*1.257909, digital(<...","today(<to,tod,oda,day,ay>)*-1.214953, digital(...","today(<to,tod,oda,day,ay>)*0.490591, digital(<...","today(<to,tod,oda,day,ay>)*1.461841, digital(<...","today(<to,tod,oda,day,ay>)*-0.330407, digital(...","today(<to,tod,oda,day,ay>)*0.483026, digital(<...","today(<to,tod,oda,day,ay>)*-0.753672, digital(...","today(<to,tod,oda,day,ay>)*0.941733, digital(<...","today(<to,tod,oda,day,ay>)*1.264964, digital(<...","today(<to,tod,oda,day,ay>)*0.224133, digital(<..."
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,cbow,100,5,"sentiment(<se,sen,ent,nti,tim)*1.690143, sa(<s...","sentiment(<se,sen,ent,nti,tim)*-0.097756, sa(<...","sentiment(<se,sen,ent,nti,tim)*2.544813, sa(<s...","sentiment(<se,sen,ent,nti,tim)*0.635019, sa(<s...",...,"sentiment(<se,sen,ent,nti,tim)*0.821998, sa(<s...","sentiment(<se,sen,ent,nti,tim)*-2.340404, sa(<...","sentiment(<se,sen,ent,nti,tim)*0.080565, sa(<s...","sentiment(<se,sen,ent,nti,tim)*-0.567647, sa(<...","sentiment(<se,sen,ent,nti,tim)*0.374873, sa(<s...","sentiment(<se,sen,ent,nti,tim)*0.501785, sa(<s...","sentiment(<se,sen,ent,nti,tim)*0.074578, sa(<s...","sentiment(<se,sen,ent,nti,tim)*-1.991806, sa(<...","sentiment(<se,sen,ent,nti,tim)*1.176329, sa(<s...","sentiment(<se,sen,ent,nti,tim)*-3.376612, sa(<..."

⚙️ menjalankan word embedding fasttext: FT_skipgram_S100_W5

⚙️ menjalankan word embedding fasttext: FT_cbow_S100_W10

⚙️ menjalankan word embedding fasttext: FT_skipgram_S100_W10

## 4.6 Fast2Vec Embedding
Menggabungkan Word2Vec dan FastText menggunakan bobot alpha dan beta.

In [16]:
print("--- MULAI EKSPERIMEN FAST2VEC ---")

preview_shown = False

# hitung total pasangan model (w2v yang punya pasangan fasttext)
paired_models = [
    w2v_key for w2v_key in trained_word2vec_models
    if w2v_key.replace("W2V_", "FT_") in trained_fasttext_models
]

total_models = len(paired_models) * len(alpha_weights)

print(f"\n📊 total model fast2vec yang akan dibentuk: {total_models}")


# fungsi fast2vec (gabungan w2v + fasttext)
def get_fast2vec_vector(tokens, w2v_wv, ft_wv, alpha):
    """
    menggabungkan vektor word2vec dan fasttext
    alpha * w2v + (1 - alpha) * fasttext
    """
    vectors = []

    for word in tokens:
        if word in w2v_wv and word in ft_wv:
            v_w2v = w2v_wv[word]
            v_ft = ft_wv[word]

            # kombinasi vektor
            v_hybrid = (alpha * v_w2v) + ((1 - alpha) * v_ft)
            vectors.append(v_hybrid)

        elif word in ft_wv:
            vectors.append(ft_wv[word])

        elif word in w2v_wv:
            vectors.append(w2v_wv[word])

    if len(vectors) == 0:
        return np.zeros(w2v_wv.vector_size)

    return np.mean(vectors, axis=0).astype(np.float32)


# loop semua model word2vec
for w2v_key, w2v_model in trained_word2vec_models.items():

    # cari pasangan fasttext dengan parameter sama
    ft_key = w2v_key.replace("W2V_", "FT_")

    if ft_key not in trained_fasttext_models:
        continue

    ft_model = trained_fasttext_models[ft_key]

    # parsing metadata dari experiment id
    arch = w2v_key.split("_")[1]
    vector_size = int(w2v_key.split("_S")[1].split("_")[0])
    window = int(w2v_key.split("_W")[-1])

    print(f"\n🔗 pasangan model: {w2v_key} + {ft_key}")

    # loop alpha
    for alpha in alpha_weights:

        beta = round(1 - alpha, 1)

        # nama eksperimen fast2vec
        f2v_id = f"F2V_{arch}_S{vector_size}_W{window}_A{alpha}_B{beta}"
        print(f"\n⚙️ menjalankan: {f2v_id}")

        # step 1: document embedding fast2vec
        document_vectors = np.array([
            get_fast2vec_vector(doc, w2v_model.wv, ft_model.wv, alpha)
            for doc in sentences
        ], dtype=np.float32)

        # step 2: simpan rekap eksperimen
        experiment_results.append({
            "model": "fast2vec",
            "architecture": arch,
            "vector_size": vector_size,
            "window": window,
            "alpha": alpha,
            "beta": beta
        })

        # step 3: dataframe embedding
        df_embedding = pd.DataFrame(
            document_vectors,
            columns=[f"dim_{i}" for i in range(vector_size)]
        )

        # metadata dokumen
        df_embedding.insert(0, "doc_id", df["doc_id"])
        df_embedding.insert(1, "clean_text", original_text.values)
        df_embedding.insert(2, "text_processed", sentences.apply(lambda x: " ".join(x)))

        # metadata eksperimen
        df_embedding.insert(3, "architecture", arch)
        df_embedding.insert(4, "vector_size", vector_size)
        df_embedding.insert(5, "window", window)
        df_embedding.insert(6, "alpha", alpha)
        df_embedding.insert(7, "beta", beta)

        # preview sekali saja
        if not preview_shown:
            print(f"\n📄 preview fast2vec embedding ({f2v_id})")
            display(df_embedding.head(3))
            preview_shown = True

        df_embedding.to_csv(
            f"embedding_results/fast2vec/doc_embedding_{f2v_id}.csv",
            index=False
        )

        del document_vectors, df_embedding
        gc.collect()

--- MULAI EKSPERIMEN FAST2VEC ---

📊 total model fast2vec yang akan dibentuk: 36

🔗 pasangan model: W2V_cbow_S100_W5 + FT_cbow_S100_W5

⚙️ menjalankan: F2V_cbow_S100_W5_A0.1_B0.9

📄 preview fast2vec embedding (F2V_cbow_S100_W5_A0.1_B0.9)

,doc_id,clean_text,text_processed,architecture,vector_size,window,alpha,beta,dim_0,dim_1,...,dim_90,dim_91,dim_92,dim_93,dim_94,dim_95,dim_96,dim_97,dim_98,dim_99
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,cbow,100,5,0.1,0.9,0.496512,-0.116165,...,0.471617,-1.043484,0.154312,-0.066771,-0.025396,-0.020319,0.313771,-0.446633,0.327646,0.014927
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,cbow,100,5,0.1,0.9,0.246882,-0.190132,...,0.381861,-0.473055,-0.211092,0.213676,-0.466740,-0.283224,-0.064636,-0.487911,-0.169128,-0.106539
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,cbow,100,5,0.1,0.9,0.386094,-0.043029,...,0.410422,-0.816750,-0.541003,0.193674,-0.381832,0.062057,-0.254919,-0.250636,-0.217113,-0.518342

⚙️ menjalankan: F2V_cbow_S100_W5_A0.2_B0.8

⚙️ menjalankan: F2V_cbow_S100_W5_A0.3_B0.7

⚙️ menjalankan: F2V_cbow_S100_W5_A0.4_B0.6

⚙️ menjalankan: F2V_cbow_S100_W5_A0.5_B0.5

⚙️ menjalankan: F2V_cbow_S100_W5_A0.6_B0.4

⚙️ menjalankan: F2V_cbow_S100_W5_A0.7_B0.3

⚙️ menjalankan: F2V_cbow_S100_W5_A0.8_B0.2

⚙️ menjalankan: F2V_cbow_S100_W5_A0.9_B0.1

🔗 pasangan model: W2V_skipgram_S100_W5 + FT_skipgram_S100_W5

⚙️ menjalankan: F2V_skipgram_S100_W5_A0.1_B0.9

⚙️ menjalankan: F2V_skipgram_S100_W5_A0.2_B0.8

⚙️ menjalankan: F2V_skipgram_S100_W5_A0.3_B0.7

⚙️ menjalankan: F2V_skipgram_S100_W5_A0.4_B0.6

⚙️ menjalankan: F2V_skipgram_S100_W5_A0.5_B0.5

⚙️ menjalankan: F2V_skipgram_S100_W5_A0.6_B0.4

⚙️ menjalankan: F2V_skipgram_S100_W5_A0.7_B0.3

⚙️ menjalankan: F2V_skipgram_S100_W5_A0.8_B0.2

⚙️ menjalankan: F2V_skipgram_S100_W5_A0.9_B0.1

🔗 pasangan model: W2V_cbow_S100_W10 + FT_cbow_S100_W10

⚙️ menjalankan: F2V_cbow_S100_W10_A0.1_B0.9

⚙️ menjalankan: F2V_cbow_S100_W10_A0.2_B0.8

⚙️ menjalankan: F2V_cbow_S100_W10_A0.3_B0.7

⚙️ menjalankan: F2V_cbow_S100_W10_A0.4_B0.6

⚙️ menjalankan: F2V_cbow_S100_W10_A0.5_B0.5

⚙️ menjalankan: F2V_cbow_S100_W10_A0.6_B0.4

⚙️ menjalankan: F2V_cbow_S100_W10_A0.7_B0.3

⚙️ menjalankan: F2V_cbow_S100_W10_A0.8_B0.2

⚙️ menjalankan: F2V_cbow_S100_W10_A0.9_B0.1

🔗 pasangan model: W2V_skipgram_S100_W10 + FT_skipgram_S100_W10

⚙️ menjalankan: F2V_skipgram_S100_W10_A0.1_B0.9

⚙️ menjalankan: F2V_skipgram_S100_W10_A0.2_B0.8

⚙️ menjalankan: F2V_skipgram_S100_W10_A0.3_B0.7

⚙️ menjalankan: F2V_skipgram_S100_W10_A0.4_B0.6

⚙️ menjalankan: F2V_skipgram_S100_W10_A0.5_B0.5

⚙️ menjalankan: F2V_skipgram_S100_W10_A0.6_B0.4

⚙️ menjalankan: F2V_skipgram_S100_W10_A0.7_B0.3

⚙️ menjalankan: F2V_skipgram_S100_W10_A0.8_B0.2

⚙️ menjalankan: F2V_skipgram_S100_W10_A0.9_B0.1

In [17]:
print("--- word embedding untuk fast2vec (hybrid trace) ---")

preview_shown = False

# generate subword (sama seperti fasttext)
def generate_subwords(word, min_n=3, max_n=6):
    word = f"<{word}>"
    subwords = []

    for n in range(min_n, max_n + 1):
        for i in range(len(word) - n + 1):
            subwords.append(word[i:i+n])

    return subwords

# loop pasangan model
for w2v_key, w2v_model in trained_word2vec_models.items():

    ft_key = w2v_key.replace("W2V_", "FT_")

    if ft_key not in trained_fasttext_models:
        continue

    ft_model = trained_fasttext_models[ft_key]

    # parsing metadata
    arch = "cbow" if "_cbow_" in w2v_key else "skipgram"
    window = int(w2v_key.split("_W")[-1])
    vector_size = w2v_model.vector_size

    w2v_wv = w2v_model.wv
    ft_wv = ft_model.wv

    sentences_words = sentences

    # loop alpha
    for alpha in alpha_weights:

        beta = round(1 - alpha, 1)

        f2v_id = f"F2V_A{alpha}_B{beta}_{w2v_key.replace('W2V_', '')}"

        print(f"\n⚙️ menjalankan word embedding fast2vec: {f2v_id}")

        # build trace per dokumen
        def build_trace(doc_tokens):

            trace_cols = []

            for i in range(vector_size):

                parts = []

                for w in doc_tokens:

                    v_w2v = w2v_wv[w] if w in w2v_wv else None
                    v_ft = ft_wv[w] if w in ft_wv else None

                    if v_w2v is not None and v_ft is not None:

                        subwords = generate_subwords(w)[:5]

                        parts.append(
                            f"{w}[{alpha}*{v_w2v[i]:.6f} + {beta}*{v_ft[i]:.6f}]"
                        )

                    elif v_ft is not None:
                        subwords = generate_subwords(w)[:5]

                        parts.append(
                            f"{w}({','.join(subwords)})*{v_ft[i]:.6f}"
                        )

                    elif v_w2v is not None:
                        parts.append(
                            f"{w}*{v_w2v[i]:.6f}"
                        )

                    else:
                        parts.append(f"{w}(oov)*0.0")

                trace_cols.append(", ".join(parts))

            return trace_cols

        # generate trace
        trace_data = [build_trace(doc) for doc in sentences_words]

        df_trace = pd.DataFrame(trace_data)
        df_trace.columns = [f"word_dim{i}" for i in range(vector_size)]

        # metadata dokumen
        df_doc = pd.DataFrame({
            "doc_id": df["doc_id"],
            "clean_text": original_text.values,
            "text_processed": sentences.apply(lambda x: " ".join(x)),
            "architecture": arch,
            "vector_size": vector_size,
            "window": window,
            "alpha": alpha,
            "beta": beta
        })

        # gabungkan
        df_final = pd.concat([df_doc, df_trace], axis=1)

        # preview sekali
        if not preview_shown:
            print(f"\n📄 preview fast2vec trace ({f2v_id})")
            display(df_final.head(2))
            preview_shown = True

        # simpan
        df_final.to_csv(
            f"word_embedding_results/fast2vec/word_embedding_trace_{f2v_id}.csv",
            index=False
        )

        # cleanup
        del df_final, df_trace
        gc.collect()

--- word embedding untuk fast2vec (hybrid trace) ---

⚙️ menjalankan word embedding fast2vec: F2V_A0.1_B0.9_cbow_S100_W5

📄 preview fast2vec trace (F2V_A0.1_B0.9_cbow_S100_W5)

,doc_id,clean_text,text_processed,architecture,vector_size,window,alpha,beta,word_dim0,word_dim1,...,word_dim90,word_dim91,word_dim92,word_dim93,word_dim94,word_dim95,word_dim96,word_dim97,word_dim98,word_dim99
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,cbow,100,5,0.1,0.9,"today[0.1*0.458382 + 0.9*-0.660936], digital[0...","today[0.1*-0.563319 + 0.9*-0.462538], digital[...",...,"today[0.1*0.243226 + 0.9*1.257909], digital[0....","today[0.1*0.245486 + 0.9*-1.214953], digital[0...","today[0.1*0.309391 + 0.9*0.490591], digital[0....","today[0.1*-0.832816 + 0.9*1.461841], digital[0...","today[0.1*-0.003359 + 0.9*-0.330407], digital[...","today[0.1*0.515344 + 0.9*0.483026], digital[0....","today[0.1*0.770448 + 0.9*-0.753672], digital[0...","today[0.1*-0.092895 + 0.9*0.941733], digital[0...","today[0.1*-0.623283 + 0.9*1.264964], digital[0...","today[0.1*-0.200658 + 0.9*0.224133], digital[0..."
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,cbow,100,5,0.1,0.9,"sentiment[0.1*-0.520728 + 0.9*1.690143], sa[0....","sentiment[0.1*-3.258090 + 0.9*-0.097756], sa[0...",...,"sentiment[0.1*-1.858012 + 0.9*0.821998], sa[0....","sentiment[0.1*0.269496 + 0.9*-2.340404], sa[0....","sentiment[0.1*-0.244459 + 0.9*0.080565], sa[0....","sentiment[0.1*-0.728475 + 0.9*-0.567647], sa[0...","sentiment[0.1*-1.997706 + 0.9*0.374873], sa[0....","sentiment[0.1*0.853283 + 0.9*0.501785], sa[0.1...","sentiment[0.1*-3.978590 + 0.9*0.074578], sa[0....","sentiment[0.1*0.041570 + 0.9*-1.991806], sa[0....","sentiment[0.1*-0.024959 + 0.9*1.176329], sa[0....","sentiment[0.1*-0.591185 + 0.9*-3.376612], sa[0..."

⚙️ menjalankan word embedding fast2vec: F2V_A0.2_B0.8_cbow_S100_W5

⚙️ menjalankan word embedding fast2vec: F2V_A0.3_B0.7_cbow_S100_W5

⚙️ menjalankan word embedding fast2vec: F2V_A0.4_B0.6_cbow_S100_W5

KeyboardInterrupt:

## 4.7 Rekap Hasil Embedding
Menampilkan seluruh konfigurasi model embedding yang telah dijalankan.

In [18]:
df_rekap = pd.DataFrame(experiment_results)
df_rekap.columns = df_rekap.columns.str.lower()

expected_cols = [
    "model",
    "dataset",
    "architecture",
    "vector_size",
    "window",
    "alpha",
    "beta"
]

for col in expected_cols:
    if col not in df_rekap.columns:
        df_rekap[col] = np.nan
df_rekap = df_rekap[expected_cols]

# hitung jumlah model
total_all = len(df_rekap)
total_per_model = df_rekap["model"].value_counts().reset_index()
total_per_model.columns = ["model", "jumlah_model"]

# detail kombinasi
df_unique = df_rekap.drop_duplicates()


print("\n📊 Ringkasan Model Embedding")
display(df_rekap.head(10))

print(f"\n Total seluruh model: {total_all}")

print("\n Jumlah model per metode:")
display(total_per_model)

print("\n Kombinasi unik eksperimen:")
display(df_unique.head(10))

📊 Ringkasan Model Embedding

      model  dataset architecture  vector_size  window  alpha  beta
0  word2vec      NaN         cbow          100       5    NaN   NaN
1  word2vec      NaN     skipgram          100       5    NaN   NaN
2  word2vec      NaN         cbow          100      10    NaN   NaN
3  word2vec      NaN     skipgram          100      10    NaN   NaN
4  fasttext      NaN         cbow          100       5    NaN   NaN
5  fasttext      NaN     skipgram          100       5    NaN   NaN
6  fasttext      NaN         cbow          100      10    NaN   NaN
7  fasttext      NaN     skipgram          100      10    NaN   NaN
8  fast2vec      NaN         cbow          100       5    0.1   0.9
9  fast2vec      NaN         cbow          100       5    0.2   0.8

 Total seluruh model: 44

 Jumlah model per metode:

      model  jumlah_model
0  fast2vec            36
1  word2vec             4
2  fasttext             4

 Kombinasi unik eksperimen:

      model  dataset architecture  vector_size  window  alpha  beta
0  word2vec      NaN         cbow          100       5    NaN   NaN
1  word2vec      NaN     skipgram          100       5    NaN   NaN
2  word2vec      NaN         cbow          100      10    NaN   NaN
3  word2vec      NaN     skipgram          100      10    NaN   NaN
4  fasttext      NaN         cbow          100       5    NaN   NaN
5  fasttext      NaN     skipgram          100       5    NaN   NaN
6  fasttext      NaN         cbow          100      10    NaN   NaN
7  fasttext      NaN     skipgram          100      10    NaN   NaN
8  fast2vec      NaN         cbow          100       5    0.1   0.9
9  fast2vec      NaN         cbow          100       5    0.2   0.8

# **05 Integrasi Fitur**

In [19]:
# folder untuk menyimpan hasil integrasi fitur
os.makedirs("embedding_results/combined_features", exist_ok=True)

## 5.1 Ambil Fitur LDA

In [20]:
df_lda = df.copy()

# ambil kolom topik (otomatis, fleksibel kalau jumlah topik berubah)
topic_cols = [col for col in df_lda.columns if col.startswith("topic_")]

# ambil matrix lda
lda_vectors = df_lda[topic_cols].values

print("jumlah topik:", len(topic_cols))
print("shape lda vector:", lda_vectors.shape)

# simpan juga metadata penting
df_lda_meta = df_lda[["doc_id", "clean_text"]].copy()

display(df_lda.head(2))

jumlah topik: 7
shape lda vector: (5050, 7)

,doc_id,clean_text,lemmatization,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topik_dominan,prob_topik,tokens
0,0,today s digital world demands about automated ...,"['today', 'digital', 'world', 'demand', 'autom...",0.382534,0.516984,0.001629,0.002900,0.034902,0.001863,0.059188,2,0.516984,"[today, digital, world, demand, automated, sen..."
1,1,sentiment analysis sa is focused on mining opi...,"['sentiment', 'sa', 'focused', 'mining', 'opin...",0.266511,0.463015,0.000791,0.001397,0.083231,0.138796,0.046260,2,0.463015,"[sentiment, sa, focused, mining, opinion, iden..."

## 5.3 Integrasi Fitur (LDA + Embedding)
Menggabungkan vektor LDA dan embedding menjadi satu fitur gabungan.

In [21]:
# ambil semua file embedding
embedding_files = glob.glob("embedding_results/word2vec/*.csv") + \
                  glob.glob("embedding_results/fasttext/*.csv") + \
                  glob.glob("embedding_results/fast2vec/*.csv")

print(f"jumlah file embedding: {len(embedding_files)}")

jumlah file embedding: 44

In [22]:
combined_count = 0

for file in embedding_files:

    print(f"\nprocessing: {file}")

    df_embed = pd.read_csv(file)

    # pastikan urutan sesuai doc_id
    df_embed = df_embed.sort_values("doc_id").reset_index(drop=True)
    df_lda_sorted = df_lda.sort_values("doc_id").reset_index(drop=True)

    # ambil kolom embedding (dim_*)
    vector_cols = [c for c in df_embed.columns if c.startswith("dim_")]

    if len(vector_cols) == 0:
        print("skip: tidak ada kolom embedding dim_*")
        continue

    embedding_vectors = df_embed[vector_cols].values

    # validasi jumlah dokumen
    if len(lda_vectors) != len(embedding_vectors):
        print("warning: jumlah dokumen tidak sama, skip")
        continue

    # gabungkan fitur
    combined_vectors = np.concatenate(
        (lda_vectors, embedding_vectors),
        axis=1
    )

    print(f"shape gabungan: {combined_vectors.shape}")

    # buat dataframe
    df_combined = pd.DataFrame(combined_vectors)

    # rename kolom → topic + embedding
    topic_names = [f"topic_{i}" for i in range(len(topic_cols))]
    embed_names = [f"emb_{i}" for i in range(len(vector_cols))]

    df_combined.columns = topic_names + embed_names

    # metadata
    df_combined.insert(0, "doc_id", df_embed["doc_id"])
    df_combined.insert(1, "clean_text", df_embed["clean_text"])
    df_combined.insert(2, "text_processed", df_embed["text_processed"])
    df_combined.insert(3, "lda_topics", len(topic_cols))

    # simpan
    base_name = os.path.basename(file).replace(".csv", "")
    output_path = f"embedding_results/combined_features/COMBINED_{base_name}.csv"

    df_combined.to_csv(output_path, index=False)

    print(f"saved → {output_path}")
    combined_count += 1

print(f"\njumlah file hasil integrasi: {combined_count}")

processing: embedding_results/word2vec/doc_embedding_W2V_cbow_S100_W10.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_W2V_cbow_S100_W10.csv

processing: embedding_results/word2vec/doc_embedding_W2V_skipgram_S100_W5.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_W2V_skipgram_S100_W5.csv

processing: embedding_results/word2vec/doc_embedding_W2V_skipgram_S100_W10.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_W2V_skipgram_S100_W10.csv

processing: embedding_results/word2vec/doc_embedding_W2V_cbow_S100_W5.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_W2V_cbow_S100_W5.csv

processing: embedding_results/fasttext/doc_embedding_FT_skipgram_S100_W10.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_FT_skipgram_S100_W10.csv

processing: embedding_results/fasttext/doc_embedding_FT_cbow_S100_W10.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_FT_cbow_S100_W10.csv

processing: embedding_results/fasttext/doc_embedding_FT_cbow_S100_W5.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_FT_cbow_S100_W5.csv

processing: embedding_results/fasttext/doc_embedding_FT_skipgram_S100_W5.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_FT_skipgram_S100_W5.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8.csv

processing: embedding_results/fast2vec/doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6.csv
shape gabungan: (5050, 107)
saved → embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6.csv

jumlah file hasil integrasi: 44

## 5.4 Preview Hasil Integrasi Fitur

- Pada tahap ini ditampilkan salah satu hasil penggabungan antara vektor distribusi topik LDA dan vektor embedding dokumen.

- Tujuannya untuk memastikan bahwa proses concatenation sudah berjalan
dengan benar dan struktur datanya sesuai.

Preview ini hanya menampilkan beberapa baris pertama dari salah satu
file hasil eksperimen.

In [23]:
combined_files = glob.glob("embedding_results/combined_features/*.csv")

# pilih file pertama sebagai contoh
sample_file = combined_files[0]

print(f"\nMenampilkan contoh file:")
print(sample_file)

df_sample = pd.read_csv(sample_file)
display(df_sample.head())

Menampilkan contoh file:
embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7.csv

,doc_id,clean_text,text_processed,lda_topics,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,...,emb_90,emb_91,emb_92,emb_93,emb_94,emb_95,emb_96,emb_97,emb_98,emb_99
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.382534,0.516984,0.001629,0.002900,0.034902,0.001863,...,-0.029827,0.011037,-0.049381,0.038314,-0.021853,0.059877,0.080547,0.036939,0.046775,0.028336
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.266511,0.463015,0.000791,0.001397,0.083231,0.138796,...,0.017545,0.084835,-0.103008,0.107697,-0.059073,0.024389,0.019616,-0.001266,-0.039837,0.007003
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.651315,0.344010,0.000732,0.001291,0.001028,0.000838,...,-0.021798,0.106006,-0.190609,0.055033,-0.063769,0.016825,0.053219,0.038078,-0.093471,0.017133
3,3,in the era of web online forums blogs and twit...,era web online forum blog twitter becoming pri...,7,0.001337,0.639947,0.001113,0.001969,0.270079,0.084360,...,-0.031002,0.058516,-0.075851,0.096975,-0.094408,0.126933,0.042837,0.034675,-0.069342,0.023441
4,4,financial and economic news is continuously mo...,financial economic news continuously monitored...,7,0.361857,0.332745,0.000809,0.057704,0.001132,0.000926,...,0.026299,0.079557,-0.054126,0.046114,-0.043032,0.077978,0.043004,-0.025336,-0.046763,-0.002614

# **05 Reduksi Dimensi**
Mengambil semua file hasil integrasi gabungan LDA + embedding yang akan dipakai untuk eksperimen.

In [24]:
combined_files = [
    f"embedding_results/combined_features/{f}"
    for f in os.listdir("embedding_results/combined_features")
    if f.endswith(".csv")
]

dicoba 3

In [25]:
print(f"jumlah file combined: {len(combined_files)}")

# parameter umap
n_components_list = [5, 10]   # sesuai kebutuhan clustering karena tidak terlalu besar
n_neighbors_list = [10, 15]   # literatur: lokal vs balance
min_dist_list = [0.1, 0.3]    # rapat vs agak menyebar

umap_results = {}

jumlah file combined: 44

## 5.1 UMAP
Mengubah data ke dimensi lebih kecil pakai UMAP dengan cosine distance.

In [26]:
print("--- mulai proses UMAP ---")

preview_count = 0
max_preview = 3

for file in combined_files:

    print(f"\n📂 processing: {file}")

    df_combined = pd.read_csv(file)

    # pisahkan metadata
    meta_cols = ["doc_id", "clean_text", "text_processed", "lda_topics"]
    df_meta = df_combined[meta_cols]

    # ambil fitur numerik
    feature_cols = [c for c in df_combined.columns if c not in meta_cols]
    X = df_combined[feature_cols].values

    # normalisasi (cosine)
    X_norm = normalize(X)

    for n_comp in n_components_list:
        for n_neigh in n_neighbors_list:
            for min_d in min_dist_list:

                exp_id = f"{os.path.basename(file).replace('.csv','')}_UMAP_C{n_comp}_N{n_neigh}_D{min_d}"

                reducer = umap.UMAP(
                    n_components=n_comp,
                    n_neighbors=n_neigh,
                    min_dist=min_d,
                    metric="cosine",
                    random_state=42
                )

                X_umap = reducer.fit_transform(X_norm)

                print(f"✔ {exp_id} → shape: {X_umap.shape}")

                # ===== buat dataframe hasil =====
                umap_cols = [f"umap_{i+1}" for i in range(n_comp)]
                df_umap = pd.DataFrame(X_umap, columns=umap_cols)

                # gabungkan dengan metadata
                df_final = pd.concat([df_meta.reset_index(drop=True),
                                      df_umap.reset_index(drop=True)], axis=1)

                # simpan ke dict
                umap_results[exp_id] = df_final

                # (opsional) simpan ke file
                # df_final.to_csv(f"umap_results/{exp_id}.csv", index=False)

                # preview terbatas
                if preview_count < max_preview:
                    print(f"\n📄 preview hasil UMAP: {exp_id}")
                    display(df_final.head(3))
                    preview_count += 1

--- mulai proses UMAP ---

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C5_N10_D0.1 → shape: (5050, 5)

📄 preview hasil UMAP: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C5_N10_D0.1

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,10.619962,8.907569,5.479846,3.103794,4.466532
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,10.745676,9.081290,5.577899,2.884119,4.086594
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,10.573461,9.753963,4.764270,3.587504,4.156340

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C5_N10_D0.3 → shape: (5050, 5)

📄 preview hasil UMAP: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C5_N10_D0.3

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,10.869165,7.790685,5.483001,3.110102,4.068720
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,11.015511,7.687621,5.580473,2.941715,3.533533
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,11.013270,8.590817,4.467937,3.365835,3.715562

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C5_N15_D0.1 → shape: (5050, 5)

📄 preview hasil UMAP: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C5_N15_D0.1

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.543972,3.759334,5.580623,3.061418,6.032372
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.300112,3.676967,5.714546,3.439198,6.236587
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.759840,4.546689,5.321767,3.383317,5.960784

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.3_B0.7_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.9_B0.1_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_W2V_skipgram_S100_W10.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W10_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W10_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W10_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W10_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W10_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W10_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W10_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W10_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.7_B0.3_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.2_B0.8_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.6_B0.4_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.1_B0.9_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.3_B0.7_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_FT_skipgram_S100_W5.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W5_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W5_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W5_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W5_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W5_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W5_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W5_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W5_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.6_B0.4_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.5_B0.5_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.5_B0.5_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.1_B0.9_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.4_B0.6_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.3_B0.7_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.4_B0.6_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_W2V_cbow_S100_W5.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W5_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W5_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W5_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W5_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W5_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W5_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W5_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W5_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_FT_cbow_S100_W10.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W10_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W10_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W10_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W10_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W10_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W10_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W10_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W10_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.8_B0.2_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.6_B0.4_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.1_B0.9_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_FT_skipgram_S100_W10.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W10_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W10_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W10_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W10_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W10_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W10_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W10_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_skipgram_S100_W10_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.7_B0.3_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.8_B0.2_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.8_B0.2_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.2_B0.8_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.9_B0.1_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.1_B0.9_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.7_B0.3_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_W2V_skipgram_S100_W5.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.5_B0.5_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.2_B0.8_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.9_B0.1_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.3_B0.7_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.8_B0.2_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.9_B0.1_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.4_B0.6_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_cbow_S100_W10_A0.2_B0.8_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_FT_cbow_S100_W5.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W5_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W5_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W5_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W5_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W5_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W5_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W5_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_FT_cbow_S100_W5_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.4_B0.6_UMAP_C10_N15_D0.3 → shape: (5050, 10)

📂 processing: embedding_results/combined_features/COMBINED_doc_embedding_W2V_cbow_S100_W10.csv

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C5_N10_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C5_N10_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C5_N15_D0.1 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C5_N15_D0.3 → shape: (5050, 5)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C10_N10_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C10_N10_D0.3 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C10_N15_D0.1 → shape: (5050, 10)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

✔ COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C10_N15_D0.3 → shape: (5050, 10)

In [27]:
# folder output
os.makedirs("embedding_results/umap", exist_ok=True)

saved_count = 0

for exp_id, X_umap in umap_results.items():

    df_umap = pd.DataFrame(X_umap, columns=[f"umap_{i}" for i in range(X_umap.shape[1])])

    df_umap.to_csv(f"embedding_results/umap/{exp_id}.csv", index=False)
    saved_count += 1

print(f"\njumlah file umap tersimpan: {saved_count}")

jumlah file umap tersimpan: 352

### PCA
Mengurangi dimensi pakai PCA

In [ ]:
# from sklearn.decomposition import PCA
# from sklearn.preprocessing import StandardScaler

# pca_results = {}

# n_components_list = [5, 10, 30, 50]

# for file in combined_files:

#     print(f"\nPCA Processing: {file}")

#     df = pd.read_csv(file)

#     # ambil fitur numerik saja
#     feature_cols = [c for c in df.columns if c not in
#                     ["doc_id", "clean_text", "text_processed", "dataset", "lda_topics"]]

#     X = df[feature_cols].values

#     # scaling dulu → penting untuk PCA
#     scaler = StandardScaler()
#     X_scaled = scaler.fit_transform(X)

#     for n in n_components_list:

#         # buat PCA
#         pca = PCA(n_components=n, random_state=42)

#         # reduksi dimensi
#         X_pca = pca.fit_transform(X_scaled)

#         # simpan hasil
#         key = f"{file}_PCA_{n}"
#         pca_results[key] = X_pca

#         print(f"PCA n_components={n} → shape: {X_pca.shape}")

# **06 Clustering**

# **06 Cluster K-Means**
Digunakan untuk mencoba beberapa jumlah cluster (k) dan menghitung nilai Silhouette & DBI dengan pendekatan 'cosine'

In [ ]:
import numpy as np
from sklearn.preprocessing import normalize
from sklearn.metrics.pairwise import cosine_similarity

def kmeans_cosine(X, k, max_iter=100, tol=1e-4, random_state=42):

    np.random.seed(random_state)

    X_norm = normalize(X)
    n_samples = X_norm.shape[0]

    # inisialisasi centroid
    random_idx = np.random.choice(n_samples, k, replace=False)
    centroids = X_norm[random_idx]

    for _ in range(max_iter):

        # similarity
        sim = cosine_similarity(X_norm, centroids)

        # assign
        labels = np.argmax(sim, axis=1)

        new_centroids = []

        for i in range(k):
            cluster_points = X_norm[labels == i]

            if len(cluster_points) == 0:
                new_centroids.append(X_norm[np.random.randint(0, n_samples)])
            else:
                new_centroids.append(np.mean(cluster_points, axis=0))

        new_centroids = normalize(np.array(new_centroids))

        # konvergensi
        if np.linalg.norm(centroids - new_centroids) < tol:
            break

        centroids = new_centroids

    return labels, centroids

In [ ]:
from sklearn.metrics import silhouette_score, davies_bouldin_score

def evaluate_kmeans_umap(df_umap, range_k=(2,10)):

    # ambil hanya kolom umap
    umap_cols = [c for c in df_umap.columns if "umap_" in c]
    X = df_umap[umap_cols].values

    results = []

    for k in range(range_k[0], range_k[1]+1):

        labels, centroids = kmeans_cosine(X, k)

        sil = silhouette_score(normalize(X), labels, metric='cosine')
        dbi = davies_bouldin_score(normalize(X), labels)

        print(f"k={k} | Silhouette={sil:.4f} | DBI={dbi:.4f}")

        results.append({
            "k": k,
            "silhouette": sil,
            "dbi": dbi
        })

    return results

In [ ]:
all_cluster_results = {}

for key, df_umap in umap_results.items():

    print(f"\n📂 Clustering: {key}")

    results = evaluate_kmeans_umap(df_umap)

    # pilih k terbaik (silhouette tertinggi)
    best_k = max(results, key=lambda x: x["silhouette"])["k"]

    print(f"✅ Best k: {best_k}")

    # ambil fitur
    umap_cols = [c for c in df_umap.columns if "umap_" in c]
    X = df_umap[umap_cols].values

    labels, _ = kmeans_cosine(X, best_k)

    # gabungkan ke dataframe
    df_result = df_umap.copy()
    df_result["cluster"] = labels

    all_cluster_results[key] = df_result

    display(df_result.head(3))

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7862 | DBI=0.6697
k=3 | Silhouette=0.6854 | DBI=0.9863
k=4 | Silhouette=0.6483 | DBI=0.8514
k=5 | Silhouette=0.6180 | DBI=0.8587
k=6 | Silhouette=0.5898 | DBI=0.9185
k=7 | Silhouette=0.5331 | DBI=1.0297
k=8 | Silhouette=0.6197 | DBI=0.8566
k=9 | Silhouette=0.6003 | DBI=0.8809
k=10 | Silhouette=0.5985 | DBI=0.9147
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.869109,8.445724,4.164492,4.281650,6.208026,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.083688,8.859046,4.842039,4.557263,6.228567,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.632093,8.845299,4.971497,4.641635,6.023027,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6966 | DBI=0.8631
k=3 | Silhouette=0.5552 | DBI=1.0615
k=4 | Silhouette=0.4804 | DBI=1.2063
k=5 | Silhouette=0.4639 | DBI=1.1475
k=6 | Silhouette=0.4761 | DBI=1.1556
k=7 | Silhouette=0.5389 | DBI=1.0625
k=8 | Silhouette=0.5552 | DBI=0.9776
k=9 | Silhouette=0.5443 | DBI=0.9756
k=10 | Silhouette=0.5369 | DBI=1.0455
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.481082,8.338076,3.690452,4.319672,7.555686,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.787600,8.647925,4.724242,4.408253,7.829095,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.416262,8.447720,5.011697,4.095253,8.095634,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.8018 | DBI=0.6028
k=3 | Silhouette=0.6322 | DBI=0.9498
k=4 | Silhouette=0.5561 | DBI=1.0379
k=5 | Silhouette=0.6144 | DBI=0.8381
k=6 | Silhouette=0.6279 | DBI=0.8323
k=7 | Silhouette=0.4602 | DBI=1.0973
k=8 | Silhouette=0.6241 | DBI=0.8439
k=9 | Silhouette=0.6099 | DBI=0.9036
k=10 | Silhouette=0.5981 | DBI=0.9180
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.675195,8.775496,4.225927,3.784992,6.687143,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.904290,9.110736,4.810195,3.793043,6.929684,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.505289,8.924850,4.884115,3.633254,7.002581,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.7323 | DBI=0.7464
k=3 | Silhouette=0.5632 | DBI=1.1228
k=4 | Silhouette=0.6020 | DBI=0.8658
k=5 | Silhouette=0.5505 | DBI=0.9938
k=6 | Silhouette=0.5558 | DBI=0.9830
k=7 | Silhouette=0.5100 | DBI=1.0369
k=8 | Silhouette=0.5262 | DBI=1.0633
k=9 | Silhouette=0.5001 | DBI=1.0905
k=10 | Silhouette=0.4822 | DBI=1.0978
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.658724,8.166099,4.444789,3.477520,7.836359,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.152486,8.044051,5.457625,3.435918,8.263200,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.684201,7.626468,5.599495,3.398650,8.226874,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7553 | DBI=0.7100
k=3 | Silhouette=0.5642 | DBI=0.8847
k=4 | Silhouette=0.5105 | DBI=0.9483
k=5 | Silhouette=0.5640 | DBI=0.8539
k=6 | Silhouette=0.7022 | DBI=0.6779
k=7 | Silhouette=0.6447 | DBI=0.8870
k=8 | Silhouette=0.6511 | DBI=0.8583
k=9 | Silhouette=0.6422 | DBI=0.8882
k=10 | Silhouette=0.6310 | DBI=0.8614
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.838973,8.279369,4.329845,6.288287,3.411367,8.202232,7.096526,2.269676,4.233197,5.799009,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.187997,8.642443,4.996688,6.308802,3.253491,8.289523,7.194674,2.434056,4.104101,5.724370,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.786198,8.631089,5.161253,6.552094,3.315421,8.378952,7.216965,2.582068,4.204666,5.703568,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6948 | DBI=0.8566
k=3 | Silhouette=0.5221 | DBI=1.0360
k=4 | Silhouette=0.4395 | DBI=1.1578
k=5 | Silhouette=0.6105 | DBI=0.8236
k=6 | Silhouette=0.6253 | DBI=0.8430
k=7 | Silhouette=0.6132 | DBI=0.8493
k=8 | Silhouette=0.5712 | DBI=0.9646
k=9 | Silhouette=0.5537 | DBI=1.0553
k=10 | Silhouette=0.5533 | DBI=1.0282
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.536421,8.097351,4.531568,6.019028,2.554415,8.487556,7.637171,1.720820,5.057283,6.489203,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.143051,8.241263,5.469488,6.139462,2.215845,8.725624,7.563231,1.878918,5.338788,6.551143,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.883000,8.259503,5.606584,6.282267,2.414923,8.697170,7.750230,2.084125,5.814687,6.851728,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7859 | DBI=0.6467
k=3 | Silhouette=0.6727 | DBI=0.9057
k=4 | Silhouette=0.6074 | DBI=0.9810
k=5 | Silhouette=0.5639 | DBI=0.9750
k=6 | Silhouette=0.5272 | DBI=1.0076
k=7 | Silhouette=0.4860 | DBI=1.1078
k=8 | Silhouette=0.6205 | DBI=0.8599
k=9 | Silhouette=0.6128 | DBI=0.9145
k=10 | Silhouette=0.6002 | DBI=0.9236
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.253613,8.481677,4.167938,3.847669,6.462002,3.610532,5.975347,4.269251,6.349144,4.139919,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.496932,8.830086,4.653439,3.754615,6.682380,3.489090,6.011495,4.163672,6.356564,4.009657,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.984064,8.747252,4.686918,3.607928,6.651723,3.558092,5.968073,4.144007,6.404195,3.875303,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S100_W10_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.7125 | DBI=0.8067
k=3 | Silhouette=0.5631 | DBI=1.1045
k=4 | Silhouette=0.5728 | DBI=0.8972
k=5 | Silhouette=0.5729 | DBI=0.9481
k=6 | Silhouette=0.5117 | DBI=1.0583
k=7 | Silhouette=0.4780 | DBI=1.1660
k=8 | Silhouette=0.5540 | DBI=1.0048
k=9 | Silhouette=0.5355 | DBI=1.0922
k=10 | Silhouette=0.5218 | DBI=1.0370
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.145715,8.522861,4.514543,3.259697,6.907529,4.025632,6.260163,4.439944,6.417159,3.948123,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.805724,8.828560,5.354108,2.888599,7.234046,3.851925,6.092522,4.866343,6.182807,4.006773,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.488767,8.860992,5.537271,2.635848,7.062853,3.830987,6.044235,5.191665,6.075953,3.571463,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7064 | DBI=0.7798
k=3 | Silhouette=0.6145 | DBI=0.9524
k=4 | Silhouette=0.6041 | DBI=0.7859
k=5 | Silhouette=0.6122 | DBI=0.8253
k=6 | Silhouette=0.6153 | DBI=0.7860
k=7 | Silhouette=0.5781 | DBI=0.8097
k=8 | Silhouette=0.6201 | DBI=0.7749
k=9 | Silhouette=0.5922 | DBI=0.7438
k=10 | Silhouette=0.5685 | DBI=0.8020
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,9.688846,9.007673,4.491634,3.214982,4.826360,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,9.859912,9.181626,4.579701,3.113771,4.148314,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,9.609998,9.847431,3.700404,3.607440,4.508804,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6044 | DBI=1.0320
k=3 | Silhouette=0.5274 | DBI=1.1587
k=4 | Silhouette=0.4198 | DBI=1.2335
k=5 | Silhouette=0.5581 | DBI=0.9682
k=6 | Silhouette=0.6046 | DBI=0.8447
k=7 | Silhouette=0.5911 | DBI=0.8606
k=8 | Silhouette=0.5717 | DBI=0.9123
k=9 | Silhouette=0.5610 | DBI=1.0069
k=10 | Silhouette=0.5348 | DBI=1.0920
✅ Best k: 6

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,9.283060,7.747683,4.309232,3.921804,4.393037,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,9.628174,7.621389,4.452621,3.925239,3.567660,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,9.189852,8.281616,3.412762,4.714862,3.804168,2

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7576 | DBI=0.6895
k=3 | Silhouette=0.6021 | DBI=1.0367
k=4 | Silhouette=0.5711 | DBI=1.0451
k=5 | Silhouette=0.6521 | DBI=0.7258
k=6 | Silhouette=0.6174 | DBI=0.8042
k=7 | Silhouette=0.6240 | DBI=0.7917
k=8 | Silhouette=0.6351 | DBI=0.7342
k=9 | Silhouette=0.6261 | DBI=0.7781
k=10 | Silhouette=0.5942 | DBI=0.8248
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,9.643139,8.824012,5.024525,6.808466,3.981377,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,9.645868,8.979734,4.935009,6.880997,4.487778,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,9.886539,9.591536,5.888536,6.568392,4.036179,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.5818 | DBI=1.0651
k=3 | Silhouette=0.5540 | DBI=1.0919
k=4 | Silhouette=0.5309 | DBI=1.0717
k=5 | Silhouette=0.5380 | DBI=0.9748
k=6 | Silhouette=0.4772 | DBI=1.0569
k=7 | Silhouette=0.6009 | DBI=0.8308
k=8 | Silhouette=0.5852 | DBI=0.8903
k=9 | Silhouette=0.5737 | DBI=0.9015
k=10 | Silhouette=0.5500 | DBI=0.9817
✅ Best k: 7

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,9.664200,7.971284,5.455867,7.439835,4.732643,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,9.375019,7.880569,5.283299,7.545830,5.272598,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,9.584875,8.596761,6.461553,6.895470,5.275847,2

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7552 | DBI=0.6944
k=3 | Silhouette=0.5753 | DBI=0.8061
k=4 | Silhouette=0.5648 | DBI=0.9493
k=5 | Silhouette=0.5908 | DBI=0.9250
k=6 | Silhouette=0.6586 | DBI=0.7664
k=7 | Silhouette=0.6421 | DBI=0.8010
k=8 | Silhouette=0.6274 | DBI=0.8298
k=9 | Silhouette=0.6221 | DBI=0.7920
k=10 | Silhouette=0.5919 | DBI=0.8459
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.220779,0.918583,5.546215,7.261255,5.076853,6.299987,6.396358,3.610488,4.943101,3.080706,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,-0.233375,0.755486,5.560025,7.399900,4.495385,6.337919,6.241186,3.604454,4.935467,3.067585,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.043067,0.148059,6.312344,6.866989,4.832460,6.236925,6.582023,3.590755,5.203794,3.014619,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6418 | DBI=0.9530
k=3 | Silhouette=0.5747 | DBI=0.9514
k=4 | Silhouette=0.5287 | DBI=1.0736
k=5 | Silhouette=0.5584 | DBI=1.0032
k=6 | Silhouette=0.5526 | DBI=0.9874
k=7 | Silhouette=0.5837 | DBI=0.8984
k=8 | Silhouette=0.5630 | DBI=0.9455
k=9 | Silhouette=0.5422 | DBI=0.9729
k=10 | Silhouette=0.5167 | DBI=1.0202
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.083585,1.866775,5.911942,6.182673,5.017332,5.983517,6.494606,3.204242,4.826256,2.714810,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,-0.170588,2.006121,5.882503,6.226358,4.361432,5.851245,6.074821,3.357993,4.699299,2.750849,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.079756,1.278307,6.947526,5.653218,4.549321,5.772235,6.599553,3.242079,4.966678,2.822487,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7225 | DBI=0.7587
k=3 | Silhouette=0.6193 | DBI=0.9218
k=4 | Silhouette=0.5563 | DBI=0.9385
k=5 | Silhouette=0.6185 | DBI=0.8063
k=6 | Silhouette=0.6119 | DBI=0.8253
k=7 | Silhouette=0.6385 | DBI=0.7727
k=8 | Silhouette=0.6139 | DBI=0.8013
k=9 | Silhouette=0.6217 | DBI=0.8113
k=10 | Silhouette=0.5961 | DBI=0.8681
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,10.294397,8.751949,4.970679,2.731077,4.398997,3.962760,3.535469,6.726856,5.581700,6.661666,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,10.190907,8.972373,4.973287,2.607990,4.872375,3.847026,3.600664,6.670793,5.604317,6.646889,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,10.264217,9.482771,4.251352,3.290856,4.537735,4.056243,3.481252,6.657642,5.500575,6.749499,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W10_A0.5_B0.5_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.5916 | DBI=1.0621
k=3 | Silhouette=0.5010 | DBI=1.0442
k=4 | Silhouette=0.4222 | DBI=1.2826
k=5 | Silhouette=0.5694 | DBI=0.9796
k=6 | Silhouette=0.5973 | DBI=0.8652
k=7 | Silhouette=0.5468 | DBI=0.9796
k=8 | Silhouette=0.5787 | DBI=0.8975
k=9 | Silhouette=0.5317 | DBI=0.9674
k=10 | Silhouette=0.5070 | DBI=1.0363
✅ Best k: 6

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,10.252019,7.976885,4.831634,2.885349,4.871832,3.960641,3.644773,6.531905,5.821472,6.900271,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,10.205195,7.962943,4.844838,2.786922,5.480562,4.070839,4.001705,6.530463,5.797803,6.969398,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,10.199843,8.647829,3.943820,3.531377,5.405637,4.389756,3.451058,6.599959,5.710107,6.959695,2

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7246 | DBI=0.7752
k=3 | Silhouette=0.6121 | DBI=0.9374
k=4 | Silhouette=0.5459 | DBI=0.9775
k=5 | Silhouette=0.6538 | DBI=0.7917
k=6 | Silhouette=0.6773 | DBI=0.7213
k=7 | Silhouette=0.6490 | DBI=0.7672
k=8 | Silhouette=0.6398 | DBI=0.7923
k=9 | Silhouette=0.6301 | DBI=0.7910
k=10 | Silhouette=0.5990 | DBI=0.8577
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.019630,2.397228,4.342868,6.333067,4.590302,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.128392,2.201230,4.411996,6.463037,4.125971,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.038608,1.869335,5.524120,5.799688,4.181729,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.5550 | DBI=1.1824
k=3 | Silhouette=0.5610 | DBI=0.9659
k=4 | Silhouette=0.5484 | DBI=1.0109
k=5 | Silhouette=0.5637 | DBI=0.9241
k=6 | Silhouette=0.5581 | DBI=0.9024
k=7 | Silhouette=0.5883 | DBI=0.8921
k=8 | Silhouette=0.5694 | DBI=0.9180
k=9 | Silhouette=0.5528 | DBI=0.9792
k=10 | Silhouette=0.5224 | DBI=1.0436
✅ Best k: 7

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.410823,3.209929,4.209558,5.490466,4.104939,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.817734,3.422827,4.345198,5.596046,3.580736,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.583859,2.847871,5.779406,5.219014,3.776713,2

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7274 | DBI=0.7397
k=3 | Silhouette=0.6437 | DBI=0.8698
k=4 | Silhouette=0.5875 | DBI=0.8651
k=5 | Silhouette=0.6488 | DBI=0.7666
k=6 | Silhouette=0.6321 | DBI=0.7749
k=7 | Silhouette=0.6419 | DBI=0.7460
k=8 | Silhouette=0.6376 | DBI=0.7739
k=9 | Silhouette=0.6242 | DBI=0.7925
k=10 | Silhouette=0.5833 | DBI=0.8670
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,10.773580,9.149149,5.219862,3.343759,4.584224,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,11.017124,9.200039,5.182838,3.164438,5.056624,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,11.296339,9.245174,4.207547,3.795107,4.826763,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.5619 | DBI=1.1164
k=3 | Silhouette=0.4842 | DBI=1.0036
k=4 | Silhouette=0.5561 | DBI=1.0010
k=5 | Silhouette=0.5637 | DBI=0.9539
k=6 | Silhouette=0.5585 | DBI=0.9491
k=7 | Silhouette=0.5475 | DBI=0.9502
k=8 | Silhouette=0.5746 | DBI=0.8843
k=9 | Silhouette=0.5265 | DBI=0.9249
k=10 | Silhouette=0.5001 | DBI=1.0209
✅ Best k: 8

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,10.444960,10.387859,5.508483,4.071835,4.721632,7
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,10.302228,10.535239,5.380613,3.849833,5.375860,7
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,10.765272,10.347582,4.223107,4.592033,5.029552,2

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7441 | DBI=0.7222
k=3 | Silhouette=0.6370 | DBI=0.9767
k=4 | Silhouette=0.5125 | DBI=1.1113
k=5 | Silhouette=0.6058 | DBI=0.9179
k=6 | Silhouette=0.5514 | DBI=0.9380
k=7 | Silhouette=0.6569 | DBI=0.7691
k=8 | Silhouette=0.6306 | DBI=0.8076
k=9 | Silhouette=0.6326 | DBI=0.8215
k=10 | Silhouette=0.6200 | DBI=0.8273
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.035362,2.975137,3.820281,3.788933,4.839991,3.974583,7.268009,3.174885,3.835200,4.639641,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,-0.141692,2.728578,3.836570,3.688252,5.305261,3.845634,7.172270,3.114595,3.785407,4.590493,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.081503,2.402614,4.826585,3.916481,5.185040,4.034143,7.469067,3.157156,3.945889,4.853105,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6167 | DBI=1.0156
k=3 | Silhouette=0.5736 | DBI=0.9456
k=4 | Silhouette=0.5136 | DBI=1.0803
k=5 | Silhouette=0.5478 | DBI=1.0083
k=6 | Silhouette=0.6439 | DBI=0.8002
k=7 | Silhouette=0.5788 | DBI=0.9682
k=8 | Silhouette=0.5469 | DBI=0.9872
k=9 | Silhouette=0.5715 | DBI=0.8927
k=10 | Silhouette=0.5602 | DBI=0.9365
✅ Best k: 6

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.300847,3.453048,4.088758,4.345984,5.600443,3.896778,7.540208,3.012397,4.309568,4.023843,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,-0.305801,3.583488,4.213512,4.348472,6.203116,3.942946,7.208291,2.975634,4.267775,4.005875,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.400998,3.170699,5.483113,4.553355,5.970302,4.084772,7.720375,3.054870,4.373264,3.951701,2

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7188 | DBI=0.7633
k=3 | Silhouette=0.6229 | DBI=0.9194
k=4 | Silhouette=0.5683 | DBI=0.9104
k=5 | Silhouette=0.6409 | DBI=0.7812
k=6 | Silhouette=0.6353 | DBI=0.7938
k=7 | Silhouette=0.5991 | DBI=0.8161
k=8 | Silhouette=0.6333 | DBI=0.7968
k=9 | Silhouette=0.6162 | DBI=0.7972
k=10 | Silhouette=0.5833 | DBI=0.8580
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,10.825325,9.809323,5.750068,3.598716,4.300681,3.690246,3.031898,6.766124,6.219959,4.292377,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,11.077200,9.813826,5.754794,3.510516,4.811678,3.503435,3.104678,6.750334,6.278430,4.424478,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,11.528602,9.712142,4.764521,3.737155,4.624389,3.832214,2.802151,6.685404,5.971928,4.202245,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S100_W5_A0.6_B0.4_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.5893 | DBI=1.0684
k=3 | Silhouette=0.5110 | DBI=1.0278
k=4 | Silhouette=0.5149 | DBI=1.0969
k=5 | Silhouette=0.5609 | DBI=0.9749
k=6 | Silhouette=0.5617 | DBI=0.9508
k=7 | Silhouette=0.5444 | DBI=0.9892
k=8 | Silhouette=0.5972 | DBI=0.8963
k=9 | Silhouette=0.5584 | DBI=0.9370
k=10 | Silhouette=0.5253 | DBI=1.0406
✅ Best k: 8

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,10.311430,9.435266,5.071540,4.236699,4.459845,3.901035,3.399402,6.586122,5.842551,4.234981,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,10.240678,9.406927,4.964376,4.106702,5.155628,3.975092,3.682800,6.647198,5.871170,4.398646,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,10.606886,9.395249,3.792907,4.782086,4.959399,4.345320,3.272658,6.595976,5.855542,4.285452,2

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S300_W5_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7692 | DBI=0.6632
k=3 | Silhouette=0.6685 | DBI=0.8775
k=4 | Silhouette=0.6599 | DBI=0.7113
k=5 | Silhouette=0.7036 | DBI=0.6220
k=6 | Silhouette=0.7029 | DBI=0.6580
k=7 | Silhouette=0.6508 | DBI=0.7775
k=8 | Silhouette=0.6562 | DBI=0.7665
k=9 | Silhouette=0.6504 | DBI=0.7740
k=10 | Silhouette=0.6127 | DBI=0.8685
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.579796,7.359066,6.390075,5.540088,8.923584,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,1.686675,7.991828,5.788385,5.475416,8.969176,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.389930,8.041057,5.614562,5.767540,9.197556,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S300_W5_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6983 | DBI=0.8312
k=3 | Silhouette=0.5439 | DBI=1.0172
k=4 | Silhouette=0.5718 | DBI=0.8747
k=5 | Silhouette=0.4933 | DBI=1.0791
k=6 | Silhouette=0.4876 | DBI=1.0652
k=7 | Silhouette=0.5858 | DBI=0.9292
k=8 | Silhouette=0.5925 | DBI=0.8933
k=9 | Silhouette=0.5755 | DBI=0.9092
k=10 | Silhouette=0.5576 | DBI=0.9416
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.213569,7.727181,6.265682,6.207665,8.007424,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.718198,8.187457,5.018187,6.346405,7.727264,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.416545,8.112450,4.705303,6.711966,7.953687,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S300_W5_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7704 | DBI=0.6201
k=3 | Silhouette=0.6221 | DBI=0.8220
k=4 | Silhouette=0.6228 | DBI=0.8613
k=5 | Silhouette=0.6871 | DBI=0.7078
k=6 | Silhouette=0.6216 | DBI=0.8127
k=7 | Silhouette=0.6168 | DBI=0.8161
k=8 | Silhouette=0.6343 | DBI=0.7797
k=9 | Silhouette=0.6010 | DBI=0.8559
k=10 | Silhouette=0.6071 | DBI=0.8143
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.366139,0.837914,6.385632,5.857205,3.629527,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.136832,0.307850,5.707089,5.855475,3.391701,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.529118,0.360270,5.560255,6.028136,3.435437,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S300_W5_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.6909 | DBI=0.8008
k=3 | Silhouette=0.6217 | DBI=0.9360
k=4 | Silhouette=0.5476 | DBI=0.9944
k=5 | Silhouette=0.5852 | DBI=0.8817
k=6 | Silhouette=0.5357 | DBI=1.0065
k=7 | Silhouette=0.5091 | DBI=1.0779
k=8 | Silhouette=0.5249 | DBI=0.9973
k=9 | Silhouette=0.5206 | DBI=1.0011
k=10 | Silhouette=0.5065 | DBI=1.0818
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,5.395396,1.350779,6.445912,6.037715,2.765207,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,5.988358,1.456980,5.469517,6.189721,2.153644,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,6.337284,1.793859,5.429938,6.431618,1.877476,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S300_W5_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7595 | DBI=0.6885
k=3 | Silhouette=0.6670 | DBI=0.8913
k=4 | Silhouette=0.6525 | DBI=0.7215
k=5 | Silhouette=0.6929 | DBI=0.6423
k=6 | Silhouette=0.6894 | DBI=0.6965
k=7 | Silhouette=0.6387 | DBI=0.8128
k=8 | Silhouette=0.6375 | DBI=0.8045
k=9 | Silhouette=0.6337 | DBI=0.8127
k=10 | Silhouette=0.6151 | DBI=0.8429
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.796901,7.530154,5.894093,6.067782,9.269079,3.352742,2.615384,6.525241,4.247149,5.910416,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.067809,8.098385,5.127244,6.175209,9.379643,3.050713,2.298110,6.738210,4.268127,5.864000,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.845708,8.148551,4.986791,6.392974,9.523706,3.193357,2.244421,6.751889,4.528526,5.686350,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S300_W5_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6793 | DBI=0.8821
k=3 | Silhouette=0.6095 | DBI=1.0198
k=4 | Silhouette=0.5017 | DBI=1.1730
k=5 | Silhouette=0.6019 | DBI=0.8256
k=6 | Silhouette=0.5955 | DBI=0.9015
k=7 | Silhouette=0.5562 | DBI=0.9937
k=8 | Silhouette=0.5570 | DBI=0.9686
k=9 | Silhouette=0.5424 | DBI=0.9780
k=10 | Silhouette=0.5271 | DBI=1.0087
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.647624,7.913422,5.676093,6.294602,8.877175,2.985852,2.565418,6.758136,3.788642,6.551873,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.323025,8.043439,4.460260,6.837823,8.907430,2.423143,2.409473,6.591421,3.948762,6.509459,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.036995,8.102333,4.273311,7.055018,8.800693,2.545634,2.475512,6.554362,4.358688,6.279903,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S300_W5_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7841 | DBI=0.6414
k=3 | Silhouette=0.6723 | DBI=0.9329
k=4 | Silhouette=0.6565 | DBI=0.7957
k=5 | Silhouette=0.5678 | DBI=0.8997
k=6 | Silhouette=0.6242 | DBI=0.8275
k=7 | Silhouette=0.6224 | DBI=0.8142
k=8 | Silhouette=0.6165 | DBI=0.8241
k=9 | Silhouette=0.6140 | DBI=0.8442
k=10 | Silhouette=0.5973 | DBI=0.8666
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.915503,8.787163,3.809779,3.973371,6.252017,5.682935,3.978161,5.206898,2.755052,2.801995,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.131161,9.233634,4.549006,3.945214,6.327926,5.698337,3.924558,5.141300,2.787810,2.865857,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.765584,9.183001,4.649562,3.777457,6.185455,5.687977,3.981688,5.009078,2.939815,2.969417,1

📂 Clustering: COMBINED_doc_embedding_W2V_cbow_S300_W5_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.7142 | DBI=0.8031
k=3 | Silhouette=0.6082 | DBI=1.0421
k=4 | Silhouette=0.5238 | DBI=1.1070
k=5 | Silhouette=0.5701 | DBI=0.9550
k=6 | Silhouette=0.5991 | DBI=0.8281
k=7 | Silhouette=0.5456 | DBI=0.9775
k=8 | Silhouette=0.5467 | DBI=0.9548
k=9 | Silhouette=0.5308 | DBI=0.9940
k=10 | Silhouette=0.5245 | DBI=1.0124
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.491907,8.587193,3.733220,3.548916,6.937516,6.141251,3.524649,5.223684,2.849013,3.267617,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,4.112625,8.622848,4.851130,3.178588,7.386013,6.314733,3.718402,4.803698,3.106676,3.224055,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.952078,8.724222,4.940174,3.031777,7.228372,6.309004,3.671617,4.340126,3.387622,3.063596,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W10_A0.1_B0.9_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7693 | DBI=0.6957
k=3 | Silhouette=0.7010 | DBI=0.8595
k=4 | Silhouette=0.5087 | DBI=1.1062
k=5 | Silhouette=0.6506 | DBI=0.7843
k=6 | Silhouette=0.6344 | DBI=0.7605
k=7 | Silhouette=0.6212 | DBI=0.7961
k=8 | Silhouette=0.6231 | DBI=0.7814
k=9 | Silhouette=0.6329 | DBI=0.7923
k=10 | Silhouette=0.6364 | DBI=0.7795
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.652305,2.599256,5.849897,5.179732,5.895867,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.807061,2.217884,6.263472,5.548805,6.140890,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.947675,2.739716,6.064001,5.763011,5.817535,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W10_A0.1_B0.9_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6707 | DBI=0.9003
k=3 | Silhouette=0.6204 | DBI=0.9379
k=4 | Silhouette=0.4528 | DBI=1.1275
k=5 | Silhouette=0.5690 | DBI=0.9271
k=6 | Silhouette=0.5928 | DBI=0.8554
k=7 | Silhouette=0.5787 | DBI=0.8856
k=8 | Silhouette=0.5677 | DBI=0.8750
k=9 | Silhouette=0.5627 | DBI=0.8780
k=10 | Silhouette=0.5610 | DBI=0.8723
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.620770,3.358425,5.721233,6.467799,5.444863,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,4.898798,2.758539,5.915522,6.876762,5.681625,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,4.202851,3.666541,6.074261,7.533792,5.441836,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W10_A0.1_B0.9_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7487 | DBI=0.7211
k=3 | Silhouette=0.6512 | DBI=0.9738
k=4 | Silhouette=0.5133 | DBI=1.0956
k=5 | Silhouette=0.6128 | DBI=0.8875
k=6 | Silhouette=0.6521 | DBI=0.7509
k=7 | Silhouette=0.6214 | DBI=0.7893
k=8 | Silhouette=0.6336 | DBI=0.7411
k=9 | Silhouette=0.6177 | DBI=0.7809
k=10 | Silhouette=0.6150 | DBI=0.8623
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.262689,1.345833,3.132831,6.611922,5.423853,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.405664,1.309383,2.778159,6.972813,5.170861,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.468593,0.575634,3.376761,6.615566,5.126963,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W10_A0.1_B0.9_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.6635 | DBI=0.9056
k=3 | Silhouette=0.6169 | DBI=0.9209
k=4 | Silhouette=0.5429 | DBI=1.0290
k=5 | Silhouette=0.5161 | DBI=1.0511
k=6 | Silhouette=0.5322 | DBI=0.9880
k=7 | Silhouette=0.5905 | DBI=0.8628
k=8 | Silhouette=0.5637 | DBI=0.8892
k=9 | Silhouette=0.5571 | DBI=0.8920
k=10 | Silhouette=0.5455 | DBI=0.9515
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.293304,1.849198,4.319553,6.219101,4.865741,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.769354,1.948156,3.973400,6.392965,4.510240,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.745749,1.214622,4.879224,6.086053,4.379492,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W10_A0.1_B0.9_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7455 | DBI=0.7383
k=3 | Silhouette=0.6630 | DBI=0.9109
k=4 | Silhouette=0.4559 | DBI=1.2712
k=5 | Silhouette=0.5177 | DBI=0.9246
k=6 | Silhouette=0.6945 | DBI=0.6922
k=7 | Silhouette=0.6534 | DBI=0.7640
k=8 | Silhouette=0.6229 | DBI=0.8084
k=9 | Silhouette=0.5961 | DBI=0.9165
k=10 | Silhouette=0.6211 | DBI=0.8508
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.693063,3.714228,5.963720,5.826054,6.371261,4.241706,5.074334,3.302520,5.598646,3.893859,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,4.753387,3.359324,6.331304,6.249068,6.292229,4.333103,4.989771,3.250963,5.632406,3.850471,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.996365,4.196088,6.212967,6.371840,6.243210,4.234135,5.112887,3.554486,5.450226,3.985702,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W10_A0.1_B0.9_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6312 | DBI=0.9890
k=3 | Silhouette=0.5868 | DBI=0.9598
k=4 | Silhouette=0.4379 | DBI=1.3058
k=5 | Silhouette=0.5082 | DBI=1.0691
k=6 | Silhouette=0.6103 | DBI=0.8513
k=7 | Silhouette=0.5446 | DBI=0.9212
k=8 | Silhouette=0.5655 | DBI=0.9092
k=9 | Silhouette=0.5661 | DBI=0.9502
k=10 | Silhouette=0.5394 | DBI=1.0424
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,5.308245,3.906720,5.865049,6.173079,6.276163,3.859224,5.198573,3.421363,5.356407,4.297421,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,5.537962,3.539026,6.092964,6.799534,6.309172,4.024777,5.029392,3.300017,5.544705,4.200777,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,4.656106,4.454446,6.096910,6.959254,6.519524,3.700627,5.220403,3.796329,5.256664,4.300088,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W10_A0.1_B0.9_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7492 | DBI=0.7100
k=3 | Silhouette=0.5503 | DBI=0.8343
k=4 | Silhouette=0.4575 | DBI=1.2609
k=5 | Silhouette=0.5301 | DBI=0.9257
k=6 | Silhouette=0.6838 | DBI=0.6955
k=7 | Silhouette=0.6429 | DBI=0.7644
k=8 | Silhouette=0.6147 | DBI=0.8071
k=9 | Silhouette=0.5743 | DBI=0.9196
k=10 | Silhouette=0.5662 | DBI=0.8499
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.377251,1.453052,3.623605,6.400801,4.673764,3.098846,6.494256,3.984690,3.270190,7.735800,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,-0.494319,1.374657,3.323424,6.628407,4.892786,2.730419,6.424074,4.101963,3.263690,7.680122,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.277506,0.683687,3.957046,6.680543,5.087833,3.119153,6.503527,3.927110,3.212054,7.801621,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W10_A0.1_B0.9_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.6491 | DBI=0.9431
k=3 | Silhouette=0.5867 | DBI=1.0194
k=4 | Silhouette=0.4368 | DBI=1.2946
k=5 | Silhouette=0.4830 | DBI=1.0503
k=6 | Silhouette=0.6140 | DBI=0.8481
k=7 | Silhouette=0.5361 | DBI=0.9156
k=8 | Silhouette=0.5558 | DBI=0.9406
k=9 | Silhouette=0.5501 | DBI=0.9195
k=10 | Silhouette=0.5341 | DBI=1.0473
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.308058,1.967198,4.320292,6.099785,4.979562,3.332117,6.895415,3.967703,3.199825,7.952989,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,-0.272323,2.029731,3.936017,6.260579,5.263856,3.419696,6.712587,4.388601,3.260005,8.169663,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.482961,1.307923,4.580457,6.161812,5.789052,3.711453,6.909050,3.966515,3.370647,8.041348,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7762 | DBI=0.6162
k=3 | Silhouette=0.7161 | DBI=0.7334
k=4 | Silhouette=0.6096 | DBI=0.9135
k=5 | Silhouette=0.5021 | DBI=1.0131
k=6 | Silhouette=0.5811 | DBI=0.8986
k=7 | Silhouette=0.4476 | DBI=1.0825
k=8 | Silhouette=0.5889 | DBI=0.8590
k=9 | Silhouette=0.5924 | DBI=0.8681
k=10 | Silhouette=0.5967 | DBI=0.8959
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.868253,1.378090,7.957416,7.948766,0.475467,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.630054,1.424098,7.156006,8.149833,0.215278,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.954105,1.556043,6.989144,8.463343,-0.034827,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6987 | DBI=0.7935
k=3 | Silhouette=0.6346 | DBI=0.9251
k=4 | Silhouette=0.6533 | DBI=0.7674
k=5 | Silhouette=0.5633 | DBI=0.9680
k=6 | Silhouette=0.5105 | DBI=1.0519
k=7 | Silhouette=0.4934 | DBI=1.0597
k=8 | Silhouette=0.4817 | DBI=1.0851
k=9 | Silhouette=0.5034 | DBI=1.0056
k=10 | Silhouette=0.4937 | DBI=1.0492
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.156758,1.311610,7.389683,8.449818,0.570708,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.687781,2.107371,6.436314,8.284674,0.551453,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.123944,2.507469,6.224473,8.633820,0.479011,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7797 | DBI=0.6222
k=3 | Silhouette=0.6339 | DBI=0.7942
k=4 | Silhouette=0.6810 | DBI=0.6635
k=5 | Silhouette=0.6514 | DBI=0.7486
k=6 | Silhouette=0.6821 | DBI=0.7025
k=7 | Silhouette=0.6429 | DBI=0.8025
k=8 | Silhouette=0.6388 | DBI=0.7860
k=9 | Silhouette=0.6292 | DBI=0.8076
k=10 | Silhouette=0.6189 | DBI=0.8300
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.191105,9.257093,6.166955,7.361980,6.214079,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.440293,9.329107,5.563406,7.521156,6.530251,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.007922,9.268020,5.534213,7.981886,6.615008,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.7066 | DBI=0.7938
k=3 | Silhouette=0.5856 | DBI=1.0067
k=4 | Silhouette=0.5759 | DBI=0.8538
k=5 | Silhouette=0.5429 | DBI=0.9685
k=6 | Silhouette=0.5164 | DBI=1.0523
k=7 | Silhouette=0.5985 | DBI=0.9071
k=8 | Silhouette=0.5620 | DBI=0.9396
k=9 | Silhouette=0.5451 | DBI=0.9622
k=10 | Silhouette=0.5321 | DBI=0.9815
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.095176,8.852182,6.078067,7.594513,6.492626,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.580754,8.105950,5.164278,7.270707,6.679613,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.131366,7.469786,5.220522,7.353312,6.803048,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7663 | DBI=0.6523
k=3 | Silhouette=0.6209 | DBI=0.8436
k=4 | Silhouette=0.6787 | DBI=0.6847
k=5 | Silhouette=0.6424 | DBI=0.7912
k=6 | Silhouette=0.5548 | DBI=0.9189
k=7 | Silhouette=0.5208 | DBI=0.9845
k=8 | Silhouette=0.6139 | DBI=0.8377
k=9 | Silhouette=0.6075 | DBI=0.8670
k=10 | Silhouette=0.5859 | DBI=0.8887
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.435507,1.324685,7.944680,7.446224,0.836963,6.128995,6.147307,7.208811,4.234928,1.413857,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.314860,1.323373,7.187319,7.540962,0.650923,6.171715,6.121229,7.247714,4.346072,1.453624,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.726606,1.330386,7.038449,7.827047,0.498186,5.962255,6.220527,7.184090,4.579760,1.474958,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6892 | DBI=0.8568
k=3 | Silhouette=0.5624 | DBI=0.9866
k=4 | Silhouette=0.4738 | DBI=1.1754
k=5 | Silhouette=0.5235 | DBI=1.0368
k=6 | Silhouette=0.5766 | DBI=0.9267
k=7 | Silhouette=0.5341 | DBI=1.0303
k=8 | Silhouette=0.5380 | DBI=0.9967
k=9 | Silhouette=0.5189 | DBI=1.0406
k=10 | Silhouette=0.5033 | DBI=1.0581
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.134472,1.261981,7.903796,7.882921,0.858059,6.577416,6.055243,7.173335,4.392834,1.120107,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.659229,2.048459,6.920830,7.732185,0.821988,6.986580,6.088861,7.038231,4.530355,1.296812,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,6.959435,2.152198,6.502728,7.910483,0.827304,6.704402,6.152275,6.908751,4.869910,1.415594,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7822 | DBI=0.6247
k=3 | Silhouette=0.6383 | DBI=0.7773
k=4 | Silhouette=0.5464 | DBI=0.9785
k=5 | Silhouette=0.6157 | DBI=0.8079
k=6 | Silhouette=0.6681 | DBI=0.7126
k=7 | Silhouette=0.6203 | DBI=0.8345
k=8 | Silhouette=0.6196 | DBI=0.8166
k=9 | Silhouette=0.6132 | DBI=0.8336
k=10 | Silhouette=0.5912 | DBI=0.8716
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.176090,9.135684,6.298679,2.586910,4.076156,6.778015,4.417655,4.849389,2.869576,6.440607,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.374576,9.367060,5.605445,2.541001,3.953968,6.890894,4.509866,4.566645,2.864759,6.447059,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.002984,9.420727,5.461565,2.320045,4.099631,6.935065,4.604227,4.302069,2.930034,6.453610,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S100_W5_A0.7_B0.3_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.7040 | DBI=0.8132
k=3 | Silhouette=0.5564 | DBI=0.9845
k=4 | Silhouette=0.5812 | DBI=0.8637
k=5 | Silhouette=0.5484 | DBI=0.9644
k=6 | Silhouette=0.6014 | DBI=0.8848
k=7 | Silhouette=0.5637 | DBI=0.9806
k=8 | Silhouette=0.5453 | DBI=0.9842
k=9 | Silhouette=0.5316 | DBI=1.0150
k=10 | Silhouette=0.5216 | DBI=1.0045
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.514240,9.023519,5.891842,2.177288,4.032433,6.717502,4.294438,4.527080,2.873136,6.144423,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,4.037595,8.734807,4.897749,2.462385,3.496705,6.985187,4.551061,4.046013,2.770913,6.135228,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.832560,8.776613,4.513800,2.266332,3.594162,6.881857,4.598260,3.602291,2.743631,6.003302,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.4_B0.6_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7329 | DBI=0.7254
k=3 | Silhouette=0.6066 | DBI=0.9691
k=4 | Silhouette=0.6326 | DBI=0.9288
k=5 | Silhouette=0.4954 | DBI=1.0877
k=6 | Silhouette=0.5008 | DBI=1.0148
k=7 | Silhouette=0.4495 | DBI=1.0792
k=8 | Silhouette=0.6314 | DBI=0.8137
k=9 | Silhouette=0.6218 | DBI=0.8186
k=10 | Silhouette=0.5810 | DBI=0.9057
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.944583,6.915753,2.390227,7.301331,9.872974,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.503966,6.137762,2.746393,6.996048,10.291020,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.709016,5.946754,3.032763,6.896505,10.568699,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.4_B0.6_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6307 | DBI=0.9618
k=3 | Silhouette=0.6060 | DBI=0.9255
k=4 | Silhouette=0.5513 | DBI=1.0750
k=5 | Silhouette=0.6297 | DBI=0.8545
k=6 | Silhouette=0.5897 | DBI=0.8752
k=7 | Silhouette=0.5438 | DBI=0.9744
k=8 | Silhouette=0.5546 | DBI=0.9269
k=9 | Silhouette=0.5496 | DBI=0.9177
k=10 | Silhouette=0.5187 | DBI=1.0060
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.466742,6.676941,2.606229,7.202950,9.779202,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.402626,6.038262,3.462966,6.356982,10.164269,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,6.529936,6.054176,3.976480,6.075853,10.412734,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.4_B0.6_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.6959 | DBI=0.8269
k=3 | Silhouette=0.6414 | DBI=0.9528
k=4 | Silhouette=0.6036 | DBI=0.8396
k=5 | Silhouette=0.6901 | DBI=0.6944
k=6 | Silhouette=0.6241 | DBI=0.7858
k=7 | Silhouette=0.6068 | DBI=0.8202
k=8 | Silhouette=0.5746 | DBI=0.9029
k=9 | Silhouette=0.6317 | DBI=0.7185
k=10 | Silhouette=0.6097 | DBI=0.7624
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.423832,3.113595,0.995219,7.160193,5.350094,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.881763,3.662197,0.875573,6.750894,5.477912,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.496141,3.772059,0.997843,6.454431,5.787558,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.4_B0.6_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.6300 | DBI=0.9743
k=3 | Silhouette=0.5448 | DBI=1.0268
k=4 | Silhouette=0.5528 | DBI=0.9553
k=5 | Silhouette=0.6181 | DBI=0.8371
k=6 | Silhouette=0.5907 | DBI=0.8241
k=7 | Silhouette=0.5430 | DBI=0.9566
k=8 | Silhouette=0.5448 | DBI=0.9687
k=9 | Silhouette=0.5366 | DBI=0.9548
k=10 | Silhouette=0.5293 | DBI=0.9627
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.330823,2.635994,1.669262,6.820320,4.512753,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.027988,3.577145,2.069779,6.331671,4.479696,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.491896,3.757574,2.552825,6.120494,4.655648,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.4_B0.6_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7384 | DBI=0.7380
k=3 | Silhouette=0.6366 | DBI=0.9924
k=4 | Silhouette=0.6637 | DBI=0.8440
k=5 | Silhouette=0.5983 | DBI=0.9103
k=6 | Silhouette=0.5442 | DBI=0.9646
k=7 | Silhouette=0.5241 | DBI=0.9548
k=8 | Silhouette=0.6089 | DBI=0.8300
k=9 | Silhouette=0.6108 | DBI=0.8449
k=10 | Silhouette=0.5890 | DBI=0.9053
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.060285,2.493055,8.133312,2.862034,9.290524,5.482109,0.977706,4.979500,5.939584,3.826611,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.414850,3.280230,8.021062,3.070950,9.052054,5.486225,0.748465,5.076343,5.959948,3.461102,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.195737,3.487191,7.807170,3.084063,8.854372,5.338281,0.620444,5.159311,5.981303,3.210004,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.4_B0.6_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6258 | DBI=1.0057
k=3 | Silhouette=0.5407 | DBI=1.1549
k=4 | Silhouette=0.5073 | DBI=1.1872
k=5 | Silhouette=0.4758 | DBI=1.1804
k=6 | Silhouette=0.4299 | DBI=1.2077
k=7 | Silhouette=0.5495 | DBI=0.9679
k=8 | Silhouette=0.5204 | DBI=1.0302
k=9 | Silhouette=0.5246 | DBI=1.0138
k=10 | Silhouette=0.5263 | DBI=1.0237
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.743850,2.496720,8.111751,2.678197,9.237000,5.931821,1.237304,5.037514,5.282865,4.346673,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.535158,3.526651,7.521571,3.080970,9.359046,6.205640,0.935670,4.825480,4.997713,3.966324,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.452408,3.613445,7.120742,3.256200,9.522666,6.187230,0.952852,4.812895,4.754724,3.538525,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.4_B0.6_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7327 | DBI=0.7406
k=3 | Silhouette=0.6165 | DBI=0.9441
k=4 | Silhouette=0.5800 | DBI=1.0071
k=5 | Silhouette=0.5257 | DBI=1.0433
k=6 | Silhouette=0.6277 | DBI=0.8561
k=7 | Silhouette=0.6192 | DBI=0.8396
k=8 | Silhouette=0.5756 | DBI=0.9306
k=9 | Silhouette=0.5742 | DBI=0.9452
k=10 | Silhouette=0.5865 | DBI=0.8873
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.626595,6.934706,0.978202,2.690846,4.766644,8.327400,4.303557,3.740235,5.269420,7.141813,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.240726,6.435739,0.768662,3.004303,4.752470,8.376811,4.215652,3.700579,5.600851,7.074961,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.565319,6.317441,0.916963,3.117523,4.541410,8.294209,4.144083,3.540539,5.836924,6.866549,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.4_B0.6_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.6230 | DBI=1.0000
k=3 | Silhouette=0.5481 | DBI=1.1056
k=4 | Silhouette=0.5568 | DBI=0.9301
k=5 | Silhouette=0.5248 | DBI=1.0496
k=6 | Silhouette=0.4487 | DBI=1.1956
k=7 | Silhouette=0.5438 | DBI=0.9812
k=8 | Silhouette=0.5185 | DBI=1.0561
k=9 | Silhouette=0.5124 | DBI=1.0724
k=10 | Silhouette=0.4984 | DBI=1.1186
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.648244,6.897506,1.723626,3.057532,5.193445,8.112122,4.688990,3.662425,5.535386,6.808759,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.784009,6.158533,2.027054,3.705381,5.498171,8.473614,4.336694,3.605080,5.739459,6.567877,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,6.918957,5.933696,2.358891,3.948042,5.454229,8.340153,4.582721,3.317574,6.120581,6.522277,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S200_W10_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7467 | DBI=0.7418
k=3 | Silhouette=0.7102 | DBI=0.8058
k=4 | Silhouette=0.4870 | DBI=1.1381
k=5 | Silhouette=0.5626 | DBI=1.0021
k=6 | Silhouette=0.6068 | DBI=0.8684
k=7 | Silhouette=0.6068 | DBI=0.8268
k=8 | Silhouette=0.6159 | DBI=0.8119
k=9 | Silhouette=0.6086 | DBI=0.8334
k=10 | Silhouette=0.5475 | DBI=0.9840
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.024577,4.826918,2.074842,7.477712,1.941105,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.648257,5.534782,2.391708,7.951479,1.824981,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.403332,5.573850,2.799514,8.109467,1.700793,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S200_W10_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.5470 | DBI=1.2272
k=3 | Silhouette=0.4945 | DBI=1.3525
k=4 | Silhouette=0.5113 | DBI=1.0442
k=5 | Silhouette=0.5541 | DBI=0.9673
k=6 | Silhouette=0.5487 | DBI=0.9487
k=7 | Silhouette=0.5542 | DBI=0.9516
k=8 | Silhouette=0.5369 | DBI=1.0005
k=9 | Silhouette=0.5131 | DBI=1.0756
k=10 | Silhouette=0.4994 | DBI=1.1319
✅ Best k: 7

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.025542,4.369282,2.116642,6.879664,1.535772,2
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.045417,5.170222,2.933295,7.266252,1.314685,2
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.774620,5.095366,3.561936,7.236355,1.207032,2

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S200_W10_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7148 | DBI=0.8027
k=3 | Silhouette=0.5977 | DBI=0.9722
k=4 | Silhouette=0.6104 | DBI=0.8936
k=5 | Silhouette=0.5504 | DBI=0.9179
k=6 | Silhouette=0.4945 | DBI=1.0032
k=7 | Silhouette=0.5808 | DBI=0.8920
k=8 | Silhouette=0.5769 | DBI=0.9007
k=9 | Silhouette=0.5633 | DBI=0.9173
k=10 | Silhouette=0.5406 | DBI=0.9583
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.852122,4.239937,1.837322,3.444938,8.798042,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.595629,5.053845,1.863806,3.366522,9.127091,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.442141,5.184653,2.056913,3.372269,9.461911,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S200_W10_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.5939 | DBI=1.1253
k=3 | Silhouette=0.6025 | DBI=0.9089
k=4 | Silhouette=0.5679 | DBI=0.9284
k=5 | Silhouette=0.5103 | DBI=1.0695
k=6 | Silhouette=0.5573 | DBI=0.9334
k=7 | Silhouette=0.5290 | DBI=0.9902
k=8 | Silhouette=0.4997 | DBI=1.1087
k=9 | Silhouette=0.4910 | DBI=1.1043
k=10 | Silhouette=0.4877 | DBI=1.1241
✅ Best k: 3

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.510190,4.040749,1.913645,2.657836,8.338259,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.589542,4.891917,2.582443,2.094509,8.559546,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.242345,4.964605,3.038981,2.116767,8.841167,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S200_W10_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7113 | DBI=0.8082
k=3 | Silhouette=0.6446 | DBI=0.9420
k=4 | Silhouette=0.5918 | DBI=0.8597
k=5 | Silhouette=0.6803 | DBI=0.7250
k=6 | Silhouette=0.6561 | DBI=0.7637
k=7 | Silhouette=0.6337 | DBI=0.7668
k=8 | Silhouette=0.5675 | DBI=0.9471
k=9 | Silhouette=0.5615 | DBI=0.9687
k=10 | Silhouette=0.5915 | DBI=0.8846
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.954354,4.939506,1.427413,6.642897,1.401783,3.366809,0.556320,6.504674,6.264121,4.085122,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.581106,5.840773,1.631570,6.892269,1.464076,3.276443,0.549922,6.539585,6.224332,3.920796,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.365919,6.057217,1.745331,7.001528,1.448061,3.342992,0.429895,6.445508,5.884738,3.700642,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S200_W10_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6075 | DBI=1.0543
k=3 | Silhouette=0.5460 | DBI=1.1499
k=4 | Silhouette=0.5247 | DBI=1.0403
k=5 | Silhouette=0.5745 | DBI=0.9331
k=6 | Silhouette=0.5532 | DBI=0.9778
k=7 | Silhouette=0.5417 | DBI=0.9931
k=8 | Silhouette=0.4932 | DBI=1.1003
k=9 | Silhouette=0.5094 | DBI=1.0515
k=10 | Silhouette=0.4963 | DBI=1.1140
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.952477,4.524357,1.621223,6.793493,1.791422,2.651230,0.953554,7.034445,5.716249,3.907680,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.109439,5.436306,2.340081,7.251826,1.579196,2.776849,1.029258,6.932683,5.727157,3.931070,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.904619,5.565944,2.766891,7.519555,1.748596,2.882362,0.995763,6.954091,5.426567,3.696902,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S200_W10_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7137 | DBI=0.7685
k=3 | Silhouette=0.6029 | DBI=0.9541
k=4 | Silhouette=0.5282 | DBI=1.1033
k=5 | Silhouette=0.6326 | DBI=0.8119
k=6 | Silhouette=0.6015 | DBI=0.9016
k=7 | Silhouette=0.5596 | DBI=0.9942
k=8 | Silhouette=0.5690 | DBI=0.9430
k=9 | Silhouette=0.5644 | DBI=0.9557
k=10 | Silhouette=0.5973 | DBI=0.8680
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.398908,5.916612,1.278964,7.173763,1.493451,6.100084,3.663380,4.160543,5.779518,6.787092,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.667831,5.167593,1.323060,7.436476,1.512473,6.117400,3.672451,3.936496,6.036938,6.841967,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,6.857221,5.057143,1.482386,7.635299,1.425996,5.971972,3.678706,3.749123,6.372639,6.845154,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S200_W10_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.6133 | DBI=1.0182
k=3 | Silhouette=0.5050 | DBI=1.0744
k=4 | Silhouette=0.5495 | DBI=0.9429
k=5 | Silhouette=0.5059 | DBI=1.1097
k=6 | Silhouette=0.5349 | DBI=1.0714
k=7 | Silhouette=0.5243 | DBI=1.0260
k=8 | Silhouette=0.5030 | DBI=1.0974
k=9 | Silhouette=0.4938 | DBI=1.1172
k=10 | Silhouette=0.4882 | DBI=1.1463
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.412829,5.830743,0.905962,6.996964,1.548004,6.375036,3.206358,4.389336,6.552432,6.621085,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.415535,4.961795,1.392160,7.265106,1.316072,6.619073,3.546044,4.006162,6.672190,6.689665,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,6.652325,4.727899,1.727698,7.365554,1.334743,6.540070,3.432160,4.076450,7.088232,6.524890,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.9_B0.1_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7902 | DBI=0.6146
k=3 | Silhouette=0.6947 | DBI=0.7380
k=4 | Silhouette=0.6157 | DBI=0.8477
k=5 | Silhouette=0.6474 | DBI=0.7572
k=6 | Silhouette=0.6744 | DBI=0.7301
k=7 | Silhouette=0.6440 | DBI=0.7340
k=8 | Silhouette=0.5947 | DBI=0.8277
k=9 | Silhouette=0.6338 | DBI=0.7964
k=10 | Silhouette=0.6096 | DBI=0.8893
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,7.587212,2.538198,4.419660,3.449829,0.31836,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,8.461894,2.168611,4.886901,3.478431,0.17321,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,8.995646,2.321217,4.976234,3.463994,0.11540,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.9_B0.1_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.7402 | DBI=0.7521
k=3 | Silhouette=0.6812 | DBI=0.8525
k=4 | Silhouette=0.5049 | DBI=1.1664
k=5 | Silhouette=0.5885 | DBI=0.9669
k=6 | Silhouette=0.6397 | DBI=0.8159
k=7 | Silhouette=0.5983 | DBI=0.9134
k=8 | Silhouette=0.5618 | DBI=0.9777
k=9 | Silhouette=0.5353 | DBI=1.0117
k=10 | Silhouette=0.5166 | DBI=1.0739
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.593850,2.343247,4.530556,3.293255,0.895330,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.231931,2.175705,5.523816,3.423858,0.694343,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.786601,2.566616,5.717699,3.525141,0.432944,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.9_B0.1_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7809 | DBI=0.6628
k=3 | Silhouette=0.6584 | DBI=0.8757
k=4 | Silhouette=0.6267 | DBI=0.9096
k=5 | Silhouette=0.5905 | DBI=0.9285
k=6 | Silhouette=0.5942 | DBI=0.9346
k=7 | Silhouette=0.5233 | DBI=1.0708
k=8 | Silhouette=0.5611 | DBI=0.9743
k=9 | Silhouette=0.5842 | DBI=0.9368
k=10 | Silhouette=0.5848 | DBI=0.9496
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.379040,8.973041,3.768710,3.429874,6.223687,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.477109,9.253795,4.078361,3.393265,6.488383,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.039226,9.181409,4.072238,3.136239,6.594975,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.9_B0.1_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.6748 | DBI=0.8884
k=3 | Silhouette=0.5866 | DBI=0.9217
k=4 | Silhouette=0.5382 | DBI=1.0508
k=5 | Silhouette=0.5238 | DBI=0.9951
k=6 | Silhouette=0.5701 | DBI=0.9400
k=7 | Silhouette=0.5205 | DBI=0.9928
k=8 | Silhouette=0.5335 | DBI=1.0008
k=9 | Silhouette=0.5427 | DBI=0.9654
k=10 | Silhouette=0.5266 | DBI=0.9739
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.329553,8.310627,3.633999,2.997108,7.153915,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.710412,7.965881,4.270918,2.767518,7.806608,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.354694,7.496273,4.368841,2.376025,7.777646,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.9_B0.1_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7646 | DBI=0.6706
k=3 | Silhouette=0.6202 | DBI=0.9257
k=4 | Silhouette=0.5093 | DBI=0.9561
k=5 | Silhouette=0.4987 | DBI=0.9966
k=6 | Silhouette=0.6798 | DBI=0.7096
k=7 | Silhouette=0.6662 | DBI=0.7170
k=8 | Silhouette=0.6155 | DBI=0.8087
k=9 | Silhouette=0.6449 | DBI=0.8435
k=10 | Silhouette=0.6218 | DBI=0.8673
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.593744,7.280365,5.803473,6.185700,9.438499,3.274098,6.477270,6.553749,4.802015,3.808642,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,1.674260,7.641444,5.371249,6.282882,9.445870,3.086810,6.532198,6.430871,4.991814,3.729424,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.229804,7.469861,5.267346,6.409164,9.513026,3.028206,6.509506,6.388921,5.232687,3.750779,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.9_B0.1_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6964 | DBI=0.8427
k=3 | Silhouette=0.5441 | DBI=1.1198
k=4 | Silhouette=0.5540 | DBI=0.9081
k=5 | Silhouette=0.5391 | DBI=0.9893
k=6 | Silhouette=0.5997 | DBI=0.8812
k=7 | Silhouette=0.5879 | DBI=0.8810
k=8 | Silhouette=0.5435 | DBI=0.9690
k=9 | Silhouette=0.5292 | DBI=0.9922
k=10 | Silhouette=0.5228 | DBI=1.0616
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.519981,7.690457,5.779246,7.188060,9.383126,2.809681,6.544353,6.451120,5.170152,4.048402,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.813060,7.868660,4.910758,7.215152,9.574636,2.448595,6.473643,6.141006,5.516753,4.002275,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.376700,7.679281,4.639223,7.392071,9.357831,2.512230,6.589432,6.172541,5.878403,4.242998,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.9_B0.1_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7638 | DBI=0.6555
k=3 | Silhouette=0.6291 | DBI=0.8596
k=4 | Silhouette=0.5803 | DBI=0.9664
k=5 | Silhouette=0.6421 | DBI=0.7727
k=6 | Silhouette=0.6135 | DBI=0.8634
k=7 | Silhouette=0.6032 | DBI=0.9199
k=8 | Silhouette=0.6366 | DBI=0.8398
k=9 | Silhouette=0.6344 | DBI=0.8566
k=10 | Silhouette=0.6135 | DBI=0.8782
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.362957,0.781644,6.135745,6.383864,3.437826,5.933182,4.817172,4.768814,2.703132,7.571330,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.270040,0.451700,5.689562,6.505017,3.157090,5.988724,4.795091,4.603458,2.807111,7.587268,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.704925,0.526725,5.628736,6.664437,3.157716,6.072291,4.807919,4.515631,2.844980,7.541615,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.9_B0.1_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.6633 | DBI=0.8893
k=3 | Silhouette=0.5733 | DBI=1.0846
k=4 | Silhouette=0.5126 | DBI=1.1242
k=5 | Silhouette=0.5225 | DBI=1.0864
k=6 | Silhouette=0.5529 | DBI=1.0042
k=7 | Silhouette=0.5778 | DBI=0.9207
k=8 | Silhouette=0.5399 | DBI=0.9934
k=9 | Silhouette=0.5335 | DBI=1.0093
k=10 | Silhouette=0.5332 | DBI=1.0686
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,5.595482,0.947837,5.765657,7.259786,3.517661,6.272804,4.925078,5.048501,3.121941,7.867668,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.234992,0.830875,4.911017,7.607271,3.147409,6.442035,5.257552,4.670983,3.438029,7.890752,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,6.540902,1.057389,4.707888,7.820488,3.282233,6.698616,5.198823,4.461175,3.585742,7.917429,1

📂 Clustering: COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7416 | DBI=0.7248
k=3 | Silhouette=0.6080 | DBI=0.9153
k=4 | Silhouette=0.5571 | DBI=1.0277
k=5 | Silhouette=0.6174 | DBI=0.8718
k=6 | Silhouette=0.5973 | DBI=0.8848
k=7 | Silhouette=0.6553 | DBI=0.7289
k=8 | Silhouette=0.6436 | DBI=0.7716
k=9 | Silhouette=0.6346 | DBI=0.7953
k=10 | Silhouette=0.6094 | DBI=0.8500
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,9.576477,8.529443,3.367561,6.447583,4.775987,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,9.518409,8.597157,3.199525,6.708121,4.344973,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,9.567892,9.257890,3.977375,6.666346,4.404630,1

📂 Clustering: COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6113 | DBI=1.0035
k=3 | Silhouette=0.5655 | DBI=1.0438
k=4 | Silhouette=0.5030 | DBI=1.0723
k=5 | Silhouette=0.5193 | DBI=1.0566
k=6 | Silhouette=0.4933 | DBI=1.0684
k=7 | Silhouette=0.5786 | DBI=0.8882
k=8 | Silhouette=0.5653 | DBI=0.9084
k=9 | Silhouette=0.5559 | DBI=0.8726
k=10 | Silhouette=0.5348 | DBI=0.9375
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,9.720718,7.467813,3.937117,6.248327,4.663369,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,9.898582,7.192906,3.763391,6.627018,4.157177,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,10.005936,7.913361,4.812741,6.742383,4.068902,1

📂 Clustering: COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.8029 | DBI=0.6347
k=3 | Silhouette=0.7638 | DBI=0.7313
k=4 | Silhouette=0.5309 | DBI=0.9861
k=5 | Silhouette=0.6757 | DBI=0.7243
k=6 | Silhouette=0.6506 | DBI=0.7057
k=7 | Silhouette=0.6211 | DBI=0.7704
k=8 | Silhouette=0.6154 | DBI=0.7768
k=9 | Silhouette=0.6069 | DBI=0.8171
k=10 | Silhouette=0.5775 | DBI=0.8786
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.724591,0.517725,1.945707,5.561051,5.580985,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,-0.883859,0.461583,1.946778,5.643159,6.035517,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-1.587045,0.667467,2.503969,5.718440,5.860666,1

📂 Clustering: COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.6907 | DBI=0.8716
k=3 | Silhouette=0.6589 | DBI=0.8840
k=4 | Silhouette=0.4269 | DBI=1.1434
k=5 | Silhouette=0.5487 | DBI=0.9783
k=6 | Silhouette=0.6256 | DBI=0.8442
k=7 | Silhouette=0.5871 | DBI=0.8593
k=8 | Silhouette=0.5744 | DBI=0.8712
k=9 | Silhouette=0.5739 | DBI=0.8768
k=10 | Silhouette=0.5479 | DBI=0.9840
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.278976,0.508547,2.445135,5.901876,5.309443,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,-0.093307,0.866597,2.431265,6.175509,5.779898,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.884382,0.963323,3.213338,6.183270,5.931760,1

📂 Clustering: COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7566 | DBI=0.7085
k=3 | Silhouette=0.5747 | DBI=0.8298
k=4 | Silhouette=0.5072 | DBI=1.1550
k=5 | Silhouette=0.6405 | DBI=0.7825
k=6 | Silhouette=0.6900 | DBI=0.6863
k=7 | Silhouette=0.6421 | DBI=0.7816
k=8 | Silhouette=0.6394 | DBI=0.8057
k=9 | Silhouette=0.6207 | DBI=0.8244
k=10 | Silhouette=0.6009 | DBI=0.8804
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.158710,1.427487,3.144332,5.927605,5.350307,2.799650,4.012200,3.918260,2.692167,4.259325,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.169117,1.317301,3.028916,6.284679,5.109562,2.513227,3.988615,4.043682,2.659362,4.291817,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.124920,0.692073,3.657444,6.245505,5.068987,2.674486,4.098176,3.819344,2.663788,4.344995,1

📂 Clustering: COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6597 | DBI=0.9357
k=3 | Silhouette=0.5070 | DBI=0.9959
k=4 | Silhouette=0.4927 | DBI=1.1805
k=5 | Silhouette=0.5485 | DBI=1.0040
k=6 | Silhouette=0.5927 | DBI=0.8968
k=7 | Silhouette=0.5744 | DBI=0.9373
k=8 | Silhouette=0.5672 | DBI=0.8976
k=9 | Silhouette=0.5508 | DBI=0.9118
k=10 | Silhouette=0.5260 | DBI=0.9901
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.055035,2.219784,3.739535,5.921902,4.182654,3.357016,3.979977,3.783288,2.643894,4.208115,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.166795,2.462198,3.709121,6.264225,3.689092,3.149508,4.022624,4.116015,2.482831,4.234125,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.086330,1.819834,4.594710,6.116015,3.467808,3.350326,4.086774,3.876615,2.588179,4.336393,1

📂 Clustering: COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7538 | DBI=0.7047
k=3 | Silhouette=0.5631 | DBI=0.8398
k=4 | Silhouette=0.5091 | DBI=1.1409
k=5 | Silhouette=0.5986 | DBI=0.9332
k=6 | Silhouette=0.6869 | DBI=0.7006
k=7 | Silhouette=0.6588 | DBI=0.7459
k=8 | Silhouette=0.6488 | DBI=0.7368
k=9 | Silhouette=0.6276 | DBI=0.7840
k=10 | Silhouette=0.6005 | DBI=0.8713
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.737673,0.392523,2.802588,6.001284,5.220145,3.215226,3.910214,3.809208,7.351410,4.358727,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,-0.846944,0.353882,2.733809,6.250759,4.897527,2.945379,3.903231,3.891851,7.490093,4.332847,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-1.492209,0.307403,3.493515,6.256516,4.755544,3.093597,3.895483,3.842526,7.393939,4.295165,1

📂 Clustering: COMBINED_doc_embedding_W2V_skipgram_S100_W5_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.6564 | DBI=0.9231
k=3 | Silhouette=0.5692 | DBI=1.0550
k=4 | Silhouette=0.5058 | DBI=1.1372
k=5 | Silhouette=0.5371 | DBI=1.0616
k=6 | Silhouette=0.5289 | DBI=1.0368
k=7 | Silhouette=0.5972 | DBI=0.8875
k=8 | Silhouette=0.5756 | DBI=0.9171
k=9 | Silhouette=0.5749 | DBI=0.8811
k=10 | Silhouette=0.5576 | DBI=0.9381
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,-0.165899,0.510521,3.146132,5.731078,4.311378,2.932834,3.868936,3.727444,7.426318,4.270326,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.033275,0.394520,3.242446,5.784923,3.804436,2.774001,3.650746,3.997086,7.234553,4.179070,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.637348,0.481859,4.142937,5.830031,3.553317,2.826731,3.673829,3.633188,7.255218,4.181695,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S300_W5_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7192 | DBI=0.7525
k=3 | Silhouette=0.6258 | DBI=0.8880
k=4 | Silhouette=0.5717 | DBI=0.9009
k=5 | Silhouette=0.5767 | DBI=0.9276
k=6 | Silhouette=0.4635 | DBI=1.0965
k=7 | Silhouette=0.4885 | DBI=0.9859
k=8 | Silhouette=0.6233 | DBI=0.7720
k=9 | Silhouette=0.6163 | DBI=0.7832
k=10 | Silhouette=0.5982 | DBI=0.8338
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,7.350947,5.640784,7.778512,7.281067,9.055576,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.653094,4.739304,7.984374,7.402685,9.195158,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.996455,4.582627,7.918150,7.901927,9.614043,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S300_W5_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6103 | DBI=1.0108
k=3 | Silhouette=0.5386 | DBI=1.0629
k=4 | Silhouette=0.4917 | DBI=1.0729
k=5 | Silhouette=0.5054 | DBI=1.0844
k=6 | Silhouette=0.5426 | DBI=0.9987
k=7 | Silhouette=0.5035 | DBI=1.0867
k=8 | Silhouette=0.5396 | DBI=1.0015
k=9 | Silhouette=0.5362 | DBI=0.9799
k=10 | Silhouette=0.5363 | DBI=0.9759
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,7.061965,5.952844,7.663951,7.028381,9.927991,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.689768,4.642474,7.621460,7.184607,9.916349,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.022834,4.435802,7.328422,7.549798,10.424975,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S300_W5_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7150 | DBI=0.7520
k=3 | Silhouette=0.6193 | DBI=0.9327
k=4 | Silhouette=0.6653 | DBI=0.7033
k=5 | Silhouette=0.6258 | DBI=0.8044
k=6 | Silhouette=0.5053 | DBI=0.9858
k=7 | Silhouette=0.6308 | DBI=0.7676
k=8 | Silhouette=0.6025 | DBI=0.7946
k=9 | Silhouette=0.5909 | DBI=0.8224
k=10 | Silhouette=0.5637 | DBI=0.8828
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.626591,6.248981,7.292163,7.101196,9.057913,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.038190,5.376525,7.527245,7.243021,9.169596,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.498603,5.270284,7.202742,7.351340,9.424320,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S300_W5_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.6368 | DBI=0.9436
k=3 | Silhouette=0.5335 | DBI=1.0079
k=4 | Silhouette=0.5034 | DBI=1.0925
k=5 | Silhouette=0.5846 | DBI=0.8663
k=6 | Silhouette=0.5501 | DBI=0.9526
k=7 | Silhouette=0.5215 | DBI=0.9735
k=8 | Silhouette=0.5499 | DBI=0.9360
k=9 | Silhouette=0.5289 | DBI=0.9557
k=10 | Silhouette=0.5211 | DBI=0.9994
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.183747,6.012752,6.508181,7.738119,8.959290,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,5.893680,4.836708,6.233288,8.220625,9.238151,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,6.202784,4.696980,5.591423,8.330605,9.358744,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S300_W5_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7170 | DBI=0.7963
k=3 | Silhouette=0.6295 | DBI=0.9968
k=4 | Silhouette=0.6120 | DBI=0.8607
k=5 | Silhouette=0.5350 | DBI=0.9372
k=6 | Silhouette=0.4977 | DBI=0.9901
k=7 | Silhouette=0.5886 | DBI=0.8860
k=8 | Silhouette=0.5855 | DBI=0.8859
k=9 | Silhouette=0.5621 | DBI=0.9100
k=10 | Silhouette=0.5592 | DBI=0.9549
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.367372,4.558444,2.529832,3.080289,1.012813,7.482470,0.685587,3.482315,5.688087,5.657054,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.161099,5.428493,2.261110,2.972055,0.979653,7.509080,0.668586,3.351352,5.757446,5.884895,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.828105,5.631888,2.409415,2.812404,0.845607,7.695027,0.727778,3.542389,5.755646,6.249027,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S300_W5_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6119 | DBI=1.0322
k=3 | Silhouette=0.5276 | DBI=1.0841
k=4 | Silhouette=0.5384 | DBI=0.9979
k=5 | Silhouette=0.5756 | DBI=0.8597
k=6 | Silhouette=0.5607 | DBI=0.9432
k=7 | Silhouette=0.5280 | DBI=1.0019
k=8 | Silhouette=0.5095 | DBI=1.0554
k=9 | Silhouette=0.4858 | DBI=1.0781
k=10 | Silhouette=0.4823 | DBI=1.1037
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.911734,4.697219,2.819489,3.325857,1.314447,7.413835,0.989506,3.363130,6.712601,6.300915,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.332964,5.821702,2.682369,3.353408,0.795802,7.597066,0.919790,3.422608,6.299617,6.474111,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.213917,6.072605,3.069403,3.377314,0.784249,7.684916,0.878249,3.560882,6.488403,6.970321,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S300_W5_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7014 | DBI=0.8112
k=3 | Silhouette=0.6204 | DBI=0.9407
k=4 | Silhouette=0.5721 | DBI=0.9280
k=5 | Silhouette=0.6331 | DBI=0.8177
k=6 | Silhouette=0.6232 | DBI=0.8159
k=7 | Silhouette=0.5917 | DBI=0.8570
k=8 | Silhouette=0.5782 | DBI=0.8850
k=9 | Silhouette=0.5639 | DBI=0.9152
k=10 | Silhouette=0.5584 | DBI=0.9517
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.434224,3.600390,7.835145,7.386497,8.913539,4.080073,6.237823,4.627861,5.243874,6.582946,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.965140,4.538647,7.968270,7.334677,8.892120,3.994875,6.093282,4.733401,5.502974,6.587881,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.611649,4.594712,7.691812,7.427557,8.986749,4.056442,6.061340,4.758523,5.792875,6.600006,1

📂 Clustering: COMBINED_doc_embedding_FT_cbow_S300_W5_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.5150 | DBI=1.2817
k=3 | Silhouette=0.4928 | DBI=1.1107
k=4 | Silhouette=0.5503 | DBI=0.9992
k=5 | Silhouette=0.5669 | DBI=0.9058
k=6 | Silhouette=0.5273 | DBI=1.0193
k=7 | Silhouette=0.5184 | DBI=1.0185
k=8 | Silhouette=0.4967 | DBI=1.0830
k=9 | Silhouette=0.4799 | DBI=1.1155
k=10 | Silhouette=0.4738 | DBI=1.1231
✅ Best k: 5

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.537436,3.580099,7.628327,7.080881,8.590457,3.849575,6.445718,4.737599,5.674969,5.553535,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.529204,4.658055,7.880950,6.779415,8.821136,3.927621,6.384344,4.625860,6.169915,6.194859,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.285198,4.890666,7.588986,6.848839,8.875821,3.807038,6.406144,4.515651,6.528435,6.034363,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W5_A0.2_B0.8_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7529 | DBI=0.7061
k=3 | Silhouette=0.6529 | DBI=0.8465
k=4 | Silhouette=0.6142 | DBI=0.9285
k=5 | Silhouette=0.5610 | DBI=0.9655
k=6 | Silhouette=0.5138 | DBI=1.0505
k=7 | Silhouette=0.4860 | DBI=1.0448
k=8 | Silhouette=0.4402 | DBI=1.1096
k=9 | Silhouette=0.5451 | DBI=0.9665
k=10 | Silhouette=0.5716 | DBI=0.8755
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.919753,4.531970,6.244760,2.555104,0.270679,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.497049,5.545177,6.325184,2.406945,0.225847,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.162749,5.713833,5.955755,2.158102,-0.095027,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W5_A0.2_B0.8_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6158 | DBI=1.0292
k=3 | Silhouette=0.5523 | DBI=1.0096
k=4 | Silhouette=0.5147 | DBI=1.1255
k=5 | Silhouette=0.4926 | DBI=1.0942
k=6 | Silhouette=0.4779 | DBI=1.1102
k=7 | Silhouette=0.4538 | DBI=1.1786
k=8 | Silhouette=0.5180 | DBI=0.9956
k=9 | Silhouette=0.4886 | DBI=1.0161
k=10 | Silhouette=0.5129 | DBI=0.9691
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.586289,4.520555,6.110057,3.403886,0.388507,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.927326,5.659962,5.370439,3.869179,0.424255,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.711345,5.637928,4.713906,3.932285,0.129433,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W5_A0.2_B0.8_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7333 | DBI=0.7160
k=3 | Silhouette=0.6260 | DBI=0.9904
k=4 | Silhouette=0.5614 | DBI=1.0361
k=5 | Silhouette=0.4906 | DBI=1.0777
k=6 | Silhouette=0.6255 | DBI=0.8281
k=7 | Silhouette=0.6191 | DBI=0.8012
k=8 | Silhouette=0.6064 | DBI=0.8107
k=9 | Silhouette=0.6275 | DBI=0.7575
k=10 | Silhouette=0.6253 | DBI=0.7623
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,7.000090,6.007953,7.593295,7.324372,7.975243,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.325063,5.159546,7.805737,7.323991,7.819833,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.701840,4.914176,7.684367,7.590958,8.004101,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W5_A0.2_B0.8_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.6255 | DBI=0.9825
k=3 | Silhouette=0.5198 | DBI=1.0617
k=4 | Silhouette=0.5893 | DBI=0.8531
k=5 | Silhouette=0.5399 | DBI=0.9906
k=6 | Silhouette=0.4776 | DBI=1.1276
k=7 | Silhouette=0.5617 | DBI=0.9247
k=8 | Silhouette=0.5518 | DBI=0.9523
k=9 | Silhouette=0.5249 | DBI=0.9673
k=10 | Silhouette=0.5302 | DBI=0.9782
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.396055,6.244077,6.998104,6.513075,8.697837,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.297349,4.995224,6.824542,6.609744,8.695083,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,6.644242,4.808107,6.388057,6.583045,9.061577,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W5_A0.2_B0.8_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7191 | DBI=0.7767
k=3 | Silhouette=0.6280 | DBI=0.9540
k=4 | Silhouette=0.5632 | DBI=1.0228
k=5 | Silhouette=0.4986 | DBI=1.0396
k=6 | Silhouette=0.4657 | DBI=1.0942
k=7 | Silhouette=0.6393 | DBI=0.7603
k=8 | Silhouette=0.5816 | DBI=0.8890
k=9 | Silhouette=0.5722 | DBI=0.9127
k=10 | Silhouette=0.5907 | DBI=0.8674
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.853276,4.221620,6.468045,3.052230,0.590343,1.162334,3.598344,3.999332,5.679429,5.084613,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.498973,5.122524,6.674121,3.044537,0.629242,1.143878,3.371916,4.003997,5.753263,4.801196,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.183485,5.326945,6.518676,2.900187,0.614880,1.011646,3.571776,4.109178,5.796775,4.300686,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W5_A0.2_B0.8_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.5960 | DBI=1.0854
k=3 | Silhouette=0.5133 | DBI=1.1089
k=4 | Silhouette=0.4844 | DBI=1.1958
k=5 | Silhouette=0.5134 | DBI=1.0312
k=6 | Silhouette=0.5480 | DBI=0.9696
k=7 | Silhouette=0.5349 | DBI=0.9752
k=8 | Silhouette=0.5323 | DBI=0.9869
k=9 | Silhouette=0.5139 | DBI=1.0560
k=10 | Silhouette=0.5335 | DBI=0.9709
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.144776,4.290339,6.082541,2.995479,0.584049,1.570211,3.545222,3.760080,6.158623,4.491387,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.349124,5.428637,5.938659,2.878553,0.467511,0.931575,3.446063,3.710883,5.791670,4.191414,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.198525,5.562072,5.559119,2.931366,0.472090,0.946570,3.528101,3.855722,5.860574,3.587675,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W5_A0.2_B0.8_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7075 | DBI=0.8009
k=3 | Silhouette=0.5546 | DBI=0.9437
k=4 | Silhouette=0.4126 | DBI=1.1822
k=5 | Silhouette=0.6559 | DBI=0.7659
k=6 | Silhouette=0.6309 | DBI=0.8014
k=7 | Silhouette=0.5902 | DBI=0.8605
k=8 | Silhouette=0.5782 | DBI=0.8835
k=9 | Silhouette=0.5744 | DBI=0.8938
k=10 | Silhouette=0.5872 | DBI=0.8514
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.200426,3.601767,7.864746,7.432058,7.759771,2.453992,5.287841,4.442956,4.871777,6.931502,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.713276,4.396924,8.162050,7.231075,7.889204,2.259431,5.449525,4.545243,4.934009,6.912665,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.410620,4.606133,8.073525,7.242572,8.090108,2.298352,5.276339,4.478542,5.176975,6.796219,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W5_A0.2_B0.8_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.5516 | DBI=1.1948
k=3 | Silhouette=0.5014 | DBI=1.0798
k=4 | Silhouette=0.5130 | DBI=0.9899
k=5 | Silhouette=0.5657 | DBI=0.9525
k=6 | Silhouette=0.5447 | DBI=0.9644
k=7 | Silhouette=0.5238 | DBI=0.9897
k=8 | Silhouette=0.5138 | DBI=1.0315
k=9 | Silhouette=0.4994 | DBI=1.0662
k=10 | Silhouette=0.4821 | DBI=1.0754
✅ Best k: 5

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.575258,3.383511,7.797411,7.632691,7.160686,2.836913,5.084527,4.018115,5.250450,6.682369,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.429055,4.408951,8.046295,7.256644,7.769173,2.773567,5.090808,4.158486,5.766812,6.862428,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.266536,4.604991,7.662341,7.196222,7.806726,2.815701,5.045167,3.999096,6.106212,6.582687,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S200_W10_A0.8_B0.2_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7677 | DBI=0.6556
k=3 | Silhouette=0.6765 | DBI=0.8023
k=4 | Silhouette=0.6043 | DBI=0.8969
k=5 | Silhouette=0.6143 | DBI=0.8182
k=6 | Silhouette=0.6455 | DBI=0.7977
k=7 | Silhouette=0.6256 | DBI=0.7991
k=8 | Silhouette=0.6406 | DBI=0.7994
k=9 | Silhouette=0.6277 | DBI=0.8014
k=10 | Silhouette=0.6018 | DBI=0.8642
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.304385,6.102736,6.766327,1.432179,9.525628,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,1.568438,6.302357,5.988931,1.501190,9.758901,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.250040,6.079429,5.726849,1.404144,9.808104,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S200_W10_A0.8_B0.2_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6983 | DBI=0.8399
k=3 | Silhouette=0.5403 | DBI=1.0131
k=4 | Silhouette=0.4661 | DBI=1.1598
k=5 | Silhouette=0.5561 | DBI=0.9517
k=6 | Silhouette=0.5945 | DBI=0.8806
k=7 | Silhouette=0.5859 | DBI=0.8612
k=8 | Silhouette=0.5728 | DBI=0.9043
k=9 | Silhouette=0.5555 | DBI=0.9436
k=10 | Silhouette=0.5379 | DBI=0.9887
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.318613,6.167592,6.622254,2.304566,9.639487,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.162135,5.881287,5.574473,2.538953,10.189954,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.786813,5.382861,5.360049,2.510425,10.372681,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S200_W10_A0.8_B0.2_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7351 | DBI=0.6989
k=3 | Silhouette=0.5890 | DBI=0.8641
k=4 | Silhouette=0.6179 | DBI=0.8942
k=5 | Silhouette=0.6719 | DBI=0.7507
k=6 | Silhouette=0.5931 | DBI=0.9130
k=7 | Silhouette=0.6175 | DBI=0.8311
k=8 | Silhouette=0.6153 | DBI=0.8441
k=9 | Silhouette=0.6177 | DBI=0.8164
k=10 | Silhouette=0.5863 | DBI=0.8981
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.798003,1.686737,6.535829,6.336520,3.846944,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,7.667722,1.546914,5.987960,6.473533,3.730493,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,8.060188,1.719143,5.897686,6.633465,3.766525,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S200_W10_A0.8_B0.2_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.5760 | DBI=0.9968
k=3 | Silhouette=0.5644 | DBI=1.0851
k=4 | Silhouette=0.5625 | DBI=0.9436
k=5 | Silhouette=0.5505 | DBI=1.0143
k=6 | Silhouette=0.5168 | DBI=1.0695
k=7 | Silhouette=0.4966 | DBI=1.0835
k=8 | Silhouette=0.5244 | DBI=0.9718
k=9 | Silhouette=0.5183 | DBI=1.0204
k=10 | Silhouette=0.5244 | DBI=1.0356
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.462224,1.657107,6.050744,6.897345,3.196480,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.814009,1.913456,5.044026,6.948298,2.623971,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.155602,2.358790,4.900998,7.205711,2.447588,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S200_W10_A0.8_B0.2_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7679 | DBI=0.6636
k=3 | Silhouette=0.6472 | DBI=0.8908
k=4 | Silhouette=0.4878 | DBI=1.1738
k=5 | Silhouette=0.6336 | DBI=0.8076
k=6 | Silhouette=0.6508 | DBI=0.7933
k=7 | Silhouette=0.5966 | DBI=0.9584
k=8 | Silhouette=0.6139 | DBI=0.9028
k=9 | Silhouette=0.6137 | DBI=0.9108
k=10 | Silhouette=0.6102 | DBI=0.9037
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,7.289597,3.763690,2.541597,8.184986,0.644296,6.122820,3.934520,6.595897,4.729462,5.000782,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,8.074756,3.426239,3.241039,8.333034,0.551367,6.245061,3.727328,6.485612,4.890043,5.051501,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,8.474565,3.518940,3.480721,8.385554,0.547150,6.199008,3.738786,6.399067,5.061783,5.121861,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S200_W10_A0.8_B0.2_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6848 | DBI=0.8602
k=3 | Silhouette=0.5232 | DBI=1.1001
k=4 | Silhouette=0.5717 | DBI=0.9129
k=5 | Silhouette=0.5622 | DBI=0.9720
k=6 | Silhouette=0.5814 | DBI=0.9066
k=7 | Silhouette=0.5825 | DBI=0.9162
k=8 | Silhouette=0.5503 | DBI=0.9854
k=9 | Silhouette=0.5469 | DBI=1.0180
k=10 | Silhouette=0.5237 | DBI=1.1195
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,6.560922,3.541845,2.788951,8.119288,0.278279,6.841530,4.062268,6.302046,5.163297,5.703923,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,6.905952,3.524538,3.900414,8.050951,0.357430,7.280718,3.990874,6.052389,5.386896,5.793910,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,7.265533,3.743464,4.246015,7.901079,0.450291,7.190104,3.902914,6.079462,5.747535,5.958949,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S200_W10_A0.8_B0.2_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7716 | DBI=0.6726
k=3 | Silhouette=0.6620 | DBI=0.9268
k=4 | Silhouette=0.6060 | DBI=0.9795
k=5 | Silhouette=0.5703 | DBI=0.9424
k=6 | Silhouette=0.5139 | DBI=1.0412
k=7 | Silhouette=0.6483 | DBI=0.7904
k=8 | Silhouette=0.6176 | DBI=0.8864
k=9 | Silhouette=0.6100 | DBI=0.9040
k=10 | Silhouette=0.6014 | DBI=0.8864
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.041176,8.458282,4.156372,3.267255,6.369823,5.166224,5.240286,4.446323,7.665844,6.837121,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.363918,8.556270,4.672359,3.202009,6.482953,5.202053,5.266823,4.518214,7.691836,6.772288,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.892587,8.374531,4.853254,3.193369,6.343811,5.151979,5.213648,4.679720,7.687803,6.776521,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S200_W10_A0.8_B0.2_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.6904 | DBI=0.8626
k=3 | Silhouette=0.5649 | DBI=1.0627
k=4 | Silhouette=0.5546 | DBI=1.0223
k=5 | Silhouette=0.5264 | DBI=0.9829
k=6 | Silhouette=0.4779 | DBI=1.1719
k=7 | Silhouette=0.5783 | DBI=0.9225
k=8 | Silhouette=0.5641 | DBI=0.9473
k=9 | Silhouette=0.5175 | DBI=1.0187
k=10 | Silhouette=0.5063 | DBI=1.1035
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.713889,8.259644,4.272709,2.892421,6.318527,5.086616,5.504707,4.464128,7.704423,7.267612,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.437203,8.180593,5.028285,2.646987,6.650056,5.240501,5.345304,4.761218,7.438803,7.310585,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.142953,7.890017,5.297230,2.539804,6.483352,5.267000,5.449878,5.150135,7.360217,7.757864,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S300_W5_A0.7_B0.3_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7381 | DBI=0.7223
k=3 | Silhouette=0.5390 | DBI=0.9138
k=4 | Silhouette=0.5213 | DBI=0.9988
k=5 | Silhouette=0.6404 | DBI=0.7774
k=6 | Silhouette=0.5921 | DBI=0.8041
k=7 | Silhouette=0.5916 | DBI=0.7975
k=8 | Silhouette=0.6414 | DBI=0.7341
k=9 | Silhouette=0.6393 | DBI=0.7238
k=10 | Silhouette=0.6080 | DBI=0.7904
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,10.587905,9.001178,5.273682,3.379924,4.276548,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,10.565350,9.022555,5.027542,3.367720,3.934253,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,10.347780,9.616030,4.335426,3.543004,3.964990,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S300_W5_A0.7_B0.3_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6408 | DBI=0.9285
k=3 | Silhouette=0.5211 | DBI=1.2024
k=4 | Silhouette=0.4803 | DBI=1.1916
k=5 | Silhouette=0.5352 | DBI=0.9944
k=6 | Silhouette=0.6179 | DBI=0.8018
k=7 | Silhouette=0.5927 | DBI=0.8705
k=8 | Silhouette=0.5570 | DBI=0.9482
k=9 | Silhouette=0.5515 | DBI=0.9132
k=10 | Silhouette=0.5425 | DBI=0.9032
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,9.894149,7.965081,5.350521,3.210578,4.261215,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,9.818748,7.697776,5.146938,3.259768,3.779758,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,10.146211,8.406056,4.346021,3.849115,3.630211,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S300_W5_A0.7_B0.3_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7653 | DBI=0.6911
k=3 | Silhouette=0.6796 | DBI=0.8949
k=4 | Silhouette=0.5360 | DBI=1.0990
k=5 | Silhouette=0.6638 | DBI=0.7376
k=6 | Silhouette=0.6758 | DBI=0.7396
k=7 | Silhouette=0.6456 | DBI=0.7373
k=8 | Silhouette=0.6377 | DBI=0.7645
k=9 | Silhouette=0.6394 | DBI=0.7431
k=10 | Silhouette=0.5824 | DBI=0.8319
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,1.501667,4.547369,8.356696,8.478125,3.193406,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,1.579719,4.633319,8.262258,8.715771,3.443031,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.890500,5.226135,8.533823,8.285445,3.444398,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S300_W5_A0.7_B0.3_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.6500 | DBI=0.9424
k=3 | Silhouette=0.5166 | DBI=0.9825
k=4 | Silhouette=0.5193 | DBI=1.1161
k=5 | Silhouette=0.5455 | DBI=1.0171
k=6 | Silhouette=0.5271 | DBI=0.9922
k=7 | Silhouette=0.6132 | DBI=0.8230
k=8 | Silhouette=0.5978 | DBI=0.8237
k=9 | Silhouette=0.5779 | DBI=0.8672
k=10 | Silhouette=0.5627 | DBI=0.9046
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.018034,5.089574,10.441453,8.093759,3.935424,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.321949,5.085557,10.366041,8.354074,4.287083,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.642108,5.871831,10.513655,7.564993,4.441854,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S300_W5_A0.7_B0.3_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7366 | DBI=0.7307
k=3 | Silhouette=0.6134 | DBI=0.9466
k=4 | Silhouette=0.5509 | DBI=0.9534
k=5 | Silhouette=0.6359 | DBI=0.7735
k=6 | Silhouette=0.6302 | DBI=0.7699
k=7 | Silhouette=0.6439 | DBI=0.7522
k=8 | Silhouette=0.6306 | DBI=0.7724
k=9 | Silhouette=0.6309 | DBI=0.7930
k=10 | Silhouette=0.5991 | DBI=0.8570
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,9.958849,9.086295,4.975982,3.335146,5.147616,2.560061,3.710571,7.398478,1.791969,7.210571,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,9.951103,9.070315,4.764129,3.202076,5.448571,2.580644,3.715493,7.356594,1.803188,7.186012,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,9.947789,9.666623,4.169504,3.512652,5.570441,2.847990,3.646632,7.297586,1.763986,6.992671,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S300_W5_A0.7_B0.3_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6313 | DBI=0.9739
k=3 | Silhouette=0.5467 | DBI=1.1001
k=4 | Silhouette=0.4488 | DBI=1.1773
k=5 | Silhouette=0.5216 | DBI=1.0076
k=6 | Silhouette=0.5267 | DBI=0.9862
k=7 | Silhouette=0.6005 | DBI=0.8546
k=8 | Silhouette=0.5831 | DBI=0.9093
k=9 | Silhouette=0.5517 | DBI=0.8962
k=10 | Silhouette=0.5215 | DBI=0.9778
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,9.580051,8.453362,4.641299,3.712893,5.871188,3.200202,3.762442,6.958946,1.925316,6.841313,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,9.598060,8.070907,4.411165,3.616718,6.244812,3.166227,3.874283,6.936059,1.850144,6.807985,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,9.504939,8.673412,3.622519,4.066345,6.428213,3.526887,3.416662,6.845005,1.788522,6.666483,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S300_W5_A0.7_B0.3_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7583 | DBI=0.6740
k=3 | Silhouette=0.5804 | DBI=0.8634
k=4 | Silhouette=0.6198 | DBI=0.8493
k=5 | Silhouette=0.6780 | DBI=0.7070
k=6 | Silhouette=0.6631 | DBI=0.7407
k=7 | Silhouette=0.5995 | DBI=0.8513
k=8 | Silhouette=0.5777 | DBI=0.8688
k=9 | Silhouette=0.5810 | DBI=0.9139
k=10 | Silhouette=0.5842 | DBI=0.9213
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,1.860405,4.255404,0.977181,1.718019,6.561090,4.530735,5.614117,2.733268,3.720758,2.613475,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,1.835763,4.426118,1.007394,1.674582,6.254374,4.467534,5.549758,2.714182,3.739467,2.578794,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,1.248965,5.066757,0.790978,1.938946,6.204898,4.614697,5.781748,2.817446,3.773690,2.677979,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S300_W5_A0.7_B0.3_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.6409 | DBI=0.9395
k=3 | Silhouette=0.5819 | DBI=0.8463
k=4 | Silhouette=0.5761 | DBI=0.9514
k=5 | Silhouette=0.6151 | DBI=0.8609
k=6 | Silhouette=0.5832 | DBI=0.8928
k=7 | Silhouette=0.5514 | DBI=0.9615
k=8 | Silhouette=0.5574 | DBI=0.9432
k=9 | Silhouette=0.5364 | DBI=0.9895
k=10 | Silhouette=0.4975 | DBI=1.0372
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.891375,4.581301,0.655482,2.316813,5.998679,4.357130,6.229541,2.612441,3.403601,2.740000,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.089432,4.715011,0.655091,2.207335,5.625456,4.426437,6.079411,2.544947,3.381177,2.656924,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.469184,5.572290,0.463976,2.620347,5.426388,4.620820,6.454233,2.466932,3.310803,2.809481,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W5_A0.7_B0.3_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.7161 | DBI=0.8311
k=3 | Silhouette=0.6771 | DBI=0.8474
k=4 | Silhouette=0.4376 | DBI=1.3119
k=5 | Silhouette=0.5994 | DBI=0.8618
k=6 | Silhouette=0.5560 | DBI=0.9259
k=7 | Silhouette=0.5271 | DBI=0.9507
k=8 | Silhouette=0.6493 | DBI=0.7825
k=9 | Silhouette=0.6581 | DBI=0.7526
k=10 | Silhouette=0.6187 | DBI=0.8275
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.476293,3.244996,4.749250,4.781981,5.612009,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.370098,3.315730,4.603259,5.126065,5.712273,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.835617,4.039105,4.781874,5.038104,5.509931,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W5_A0.7_B0.3_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.6028 | DBI=1.0699
k=3 | Silhouette=0.5693 | DBI=0.9734
k=4 | Silhouette=0.5399 | DBI=1.0513
k=5 | Silhouette=0.5672 | DBI=0.9277
k=6 | Silhouette=0.6348 | DBI=0.8124
k=7 | Silhouette=0.4966 | DBI=1.0075
k=8 | Silhouette=0.4957 | DBI=0.9639
k=9 | Silhouette=0.5979 | DBI=0.8744
k=10 | Silhouette=0.5539 | DBI=0.9570
✅ Best k: 6

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.295548,4.344301,5.562491,5.599346,5.906541,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,4.532665,4.398575,5.366778,6.044638,6.050850,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.967344,5.345751,5.457141,6.146931,5.549378,2

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W5_A0.7_B0.3_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.7413 | DBI=0.7375
k=3 | Silhouette=0.5756 | DBI=0.8355
k=4 | Silhouette=0.5169 | DBI=1.0943
k=5 | Silhouette=0.6173 | DBI=0.8907
k=6 | Silhouette=0.6788 | DBI=0.7258
k=7 | Silhouette=0.6667 | DBI=0.7255
k=8 | Silhouette=0.6485 | DBI=0.7770
k=9 | Silhouette=0.6558 | DBI=0.7429
k=10 | Silhouette=0.6238 | DBI=0.8027
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.326533,-0.072622,4.318525,6.838080,5.727129,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.341982,-0.149740,4.320680,7.088120,5.509955,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.253919,-0.047397,5.074674,6.688821,5.371643,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W5_A0.7_B0.3_UMAP_C5_N15_D0.3
k=2 | Silhouette=0.6284 | DBI=1.0003
k=3 | Silhouette=0.5932 | DBI=0.9385
k=4 | Silhouette=0.5434 | DBI=1.0270
k=5 | Silhouette=0.5469 | DBI=0.9875
k=6 | Silhouette=0.5569 | DBI=0.9385
k=7 | Silhouette=0.6194 | DBI=0.8379
k=8 | Silhouette=0.5914 | DBI=0.8818
k=9 | Silhouette=0.5657 | DBI=0.9439
k=10 | Silhouette=0.5395 | DBI=1.0006
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.935988,0.573842,4.122355,5.331198,4.870461,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,1.131330,0.843982,4.073962,5.593103,4.591642,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.480581,0.652935,5.081596,5.154426,4.265714,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W5_A0.7_B0.3_UMAP_C10_N10_D0.1
k=2 | Silhouette=0.7067 | DBI=0.8178
k=3 | Silhouette=0.6293 | DBI=0.9580
k=4 | Silhouette=0.5401 | DBI=1.0340
k=5 | Silhouette=0.6206 | DBI=0.8631
k=6 | Silhouette=0.6710 | DBI=0.7403
k=7 | Silhouette=0.6627 | DBI=0.7400
k=8 | Silhouette=0.6700 | DBI=0.7164
k=9 | Silhouette=0.6466 | DBI=0.7686
k=10 | Silhouette=0.6110 | DBI=0.8508
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,4.759562,3.908885,5.923195,6.030887,6.202284,4.321435,3.794992,2.971703,4.234479,3.598517,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,4.669577,4.032796,6.167453,5.669114,6.120303,4.389115,3.822422,2.990402,4.137554,3.563138,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.998543,4.670913,5.898743,5.653412,6.219046,4.025170,3.539277,3.188183,4.233302,3.561776,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W5_A0.7_B0.3_UMAP_C10_N10_D0.3
k=2 | Silhouette=0.6127 | DBI=1.0352
k=3 | Silhouette=0.4925 | DBI=1.0328
k=4 | Silhouette=0.4962 | DBI=1.1354
k=5 | Silhouette=0.5533 | DBI=0.9931
k=6 | Silhouette=0.5260 | DBI=1.0025
k=7 | Silhouette=0.6046 | DBI=0.8558
k=8 | Silhouette=0.5752 | DBI=0.9138
k=9 | Silhouette=0.5763 | DBI=0.8975
k=10 | Silhouette=0.5496 | DBI=0.9811
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,5.179613,5.144336,5.825712,5.329218,6.994397,4.528051,3.409842,3.258583,5.486630,3.427918,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,5.440256,5.267359,6.087541,4.873802,6.809021,4.810315,3.435525,3.230740,5.518157,3.387743,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,4.808965,6.285341,5.784965,4.771141,7.326831,4.512489,3.300133,3.573670,5.399683,3.275150,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W5_A0.7_B0.3_UMAP_C10_N15_D0.1
k=2 | Silhouette=0.7453 | DBI=0.7223
k=3 | Silhouette=0.5738 | DBI=0.8323
k=4 | Silhouette=0.5872 | DBI=0.9000
k=5 | Silhouette=0.6034 | DBI=0.8928
k=6 | Silhouette=0.6599 | DBI=0.7591
k=7 | Silhouette=0.6564 | DBI=0.7577
k=8 | Silhouette=0.6405 | DBI=0.7899
k=9 | Silhouette=0.6388 | DBI=0.7610
k=10 | Silhouette=0.6264 | DBI=0.7520
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.434273,0.302464,4.292262,3.912213,5.967565,3.298118,6.229708,6.994330,6.964555,2.974605,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,0.420783,0.315602,4.331951,3.708377,5.662728,3.112022,6.180892,7.069468,7.049235,3.023366,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,-0.081880,0.348731,4.989866,4.099145,5.713877,3.403316,6.384102,6.905332,6.854918,2.967571,1

📂 Clustering: COMBINED_doc_embedding_F2V_skipgram_S200_W5_A0.7_B0.3_UMAP_C10_N15_D0.3
k=2 | Silhouette=0.6336 | DBI=0.9720
k=3 | Silhouette=0.5280 | DBI=0.9954
k=4 | Silhouette=0.5423 | DBI=1.0146
k=5 | Silhouette=0.5809 | DBI=0.9399
k=6 | Silhouette=0.5904 | DBI=0.9081
k=7 | Silhouette=0.5877 | DBI=0.9122
k=8 | Silhouette=0.5715 | DBI=0.9473
k=9 | Silhouette=0.5662 | DBI=0.9404
k=10 | Silhouette=0.5443 | DBI=0.9664
✅ Best k: 2

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,umap_6,umap_7,umap_8,umap_9,umap_10,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,0.887325,-0.140247,4.210277,4.092267,4.614710,3.769528,5.563394,6.989465,6.068703,3.487949,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,1.183818,-0.063696,4.234654,3.896293,4.211353,3.748808,5.284339,6.932890,6.103848,3.451528,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,0.568676,0.028062,5.107110,4.153025,4.197613,4.047711,5.672342,7.208911,5.861790,3.849412,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.2_B0.8_UMAP_C5_N10_D0.1
k=2 | Silhouette=0.6885 | DBI=0.9995
k=3 | Silhouette=0.7739 | DBI=0.6627
k=4 | Silhouette=0.5952 | DBI=0.8514
k=5 | Silhouette=0.5527 | DBI=0.8947
k=6 | Silhouette=0.5732 | DBI=0.9035
k=7 | Silhouette=0.5602 | DBI=0.8672
k=8 | Silhouette=0.5609 | DBI=0.8821
k=9 | Silhouette=0.5450 | DBI=0.9179
k=10 | Silhouette=0.5462 | DBI=0.9668
✅ Best k: 3

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,2.876990,4.077609,1.728917,3.112761,1.602740,2
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,2.358354,4.829746,1.963493,3.366391,1.445907,2
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,2.087731,5.001047,2.143334,3.532134,1.223971,2

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.2_B0.8_UMAP_C5_N10_D0.3
k=2 | Silhouette=0.5374 | DBI=1.3564
k=3 | Silhouette=0.5999 | DBI=0.9397
k=4 | Silhouette=0.5556 | DBI=0.9889
k=5 | Silhouette=0.5431 | DBI=0.9826
k=6 | Silhouette=0.5165 | DBI=0.9767
k=7 | Silhouette=0.5265 | DBI=0.9761
k=8 | Silhouette=0.4783 | DBI=1.0849
k=9 | Silhouette=0.5140 | DBI=1.0451
k=10 | Silhouette=0.5182 | DBI=1.0797
✅ Best k: 3

,doc_id,clean_text,text_processed,lda_topics,umap_1,umap_2,umap_3,umap_4,umap_5,cluster
0,0,today s digital world demands about automated ...,today digital world demand automated sentiment...,7,3.539884,3.485415,1.624361,3.242872,2.268714,1
1,1,sentiment analysis sa is focused on mining opi...,sentiment sa focused mining opinion identifica...,7,3.384003,4.448293,2.228446,3.711924,2.223110,1
2,2,aspect based sentiment analysis absa has recen...,aspect sentiment absa recently attracted incre...,7,3.075609,4.670344,2.646086,3.907409,2.155782,1

📂 Clustering: COMBINED_doc_embedding_F2V_cbow_S300_W10_A0.2_B0.8_UMAP_C5_N15_D0.1
k=2 | Silhouette=0.6894 | DBI=0.8032
k=3 | Silhouette=0.5646 | DBI=0.9866
k=4 | Silhouette=0.5815 | DBI=0.9922

# **Cluster HDBSCAN**